### ISSUE TITLE
401 authentication error

### ISSUE THREAD

**Issue by ristp** [firebase/firebase-admin-node#1020]
I have a Node.js app running on a shared hosting. Each time I restart the app, I cannot login and I get the error "401 Unauthorized". After some research, I found out that there is a problem on the server:

Error: error:02016002:system library:stat:No such file or directory
at Sign.sign (internal/crypto/sig.js:103:29)
at Object.sign (/home/cp1183833p05/nodevenv/node-app/12/lib/node_modules/jsonwebtoken/node_modules/jwa/index.js:152:45)
at Object.jwsSign [as sign] (/home/cp1183833p05/nodevenv/node-app/12/lib/node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:32:24)
at Object.module.exports [as sign] (/home/cp1183833p05/nodevenv/node-app/12/lib/node_modules/jsonwebtoken/sign.js:204:16)
at ServiceAccountCredential.createAuthJwt_ (/home/cp1183833p05/nodevenv/node-app/12/lib/node_modules/firebase-admin/lib/auth/credential.js:103:20)
at ServiceAccountCredential.getAccessToken (/home/cp1183833p05/nodevenv/node-app/12/lib/node_modules/firebase-admin/lib/auth/credential.js:76:26)
at FirebaseAppInternals.getToken (/home/cp1183833p05/nodevenv/node-app/12/lib/node_modules/firebase-admin/lib/firebase-app.js:65:73)
at AuthorizedHttpClient.send (/home/cp1183833p05/nodevenv/node-app/12/lib/node_modules/firebase-admin/lib/utils/api-request.js:666:34)
at /home/cp1183833p05/nodevenv/node-app/12/lib/node_modules/firebase-admin/lib/auth/auth-api-request.js:1472:37
at processTicksAndRejections (internal/process/task_queues.js:97:5) {
opensslErrorStack: [
  'error:0E07606D:configuration file routines:module_run:module initialization error',
  'error:0E07B075:configuration file routines:ssl_module_init:ssl command section empty'
],
library: 'system library',
function: 'stat',
reason: 'No such file or directory',
code: 'ERR_OSSL_SYS_NO_SUCH_FILE_OR_DIRECTORY'
}

What can I do to fix this?

**Comment by hiranya911** [comment]
Looks like a broken Node.js or OpenSSL installation. You will have to work with the hosting provider to figure out why it's happening and resolve it.
