### ISSUE TITLE
Unit Testing: Module did not self-register on 5.4

### ISSUE THREAD

**Issue by zgosalvez** [firebase/firebase-admin-node#109]
### Environment

  * Operating System version: macOS High Sierra 10.13
  * Firebase SDK version: 4.5.2
  * Library version: 5.4.2
  * Firebase Product: any

#### Steps to reproduce:

1. Create a project with Cloud functions enabled.
2. Have at least the following dependencies:
  - "firebase": "^4.5.2",
  - "firebase-admin": "^5.4.2",
  - "firebase-functions": "^0.7.1",
  - "jasmine": "^2.8.0",
3. Write at least 2 spec files
4. Run `jasmine`

**Changing back firebase-admin to 5.3.0 made my unit tests run fine again.** Neither 5.4.0 or 5.4.1 resolved the issue.

#### Relevant Code:

```
Message:
    Error: Module did not self-register.
  Stack:
    Error: Module did not self-register.
        at Error (native)
        at Object.Module._extensions..node (module.js:597:18)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/builds/project/web/functions/node_modules/firebase-admin/node_modules/grpc/src/node/src/grpc_extension.js:30:15)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/builds/project/web/functions/node_modules/firebase-admin/node_modules/grpc/src/node/src/client.js:38:12)
  Message:
    TypeError: Cannot read property 'database' of undefined
  Stack:
    TypeError: Cannot read property 'database' of undefined
        at UserContext.<anonymous> (/builds/project/web/functions/triggers/database/onUserFirstNameWrite.spec.ts:37:26)
        at runCallback (timers.js:672:20)
        at tryOnImmediate (timers.js:645:5)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:386:14)
        at tryOnTimeout (timers.js:250:5)
        at Timer.listOnTimeout (timers.js:214:5)
```
Line 37 of `onUserFirstNameWrite.spec.ts` is `new functions.database.DeltaSnapshot(null, admin, null, user.first_name)`

**Comment by hiranya911** [comment]
This should be fixed now: https://firebase.google.com/support/release-notes/admin/node#5.4.3

We no longer load Firestore/gRPC packages unless `admin.firestore()` is called.

**Comment by zgosalvez** [comment]
Thank you so much, @hiranya911. This resolved this issue, but a new one emerged. Please see #122.
