### ISSUE TITLE
Error: error:25078067:DSO support routines:win32_load:could not load the shared library

### ISSUE THREAD

**Issue by udabasili** [firebase/firebase-admin-node#1182]
Let me start by saying I have followed all the protocols in step 1 and I neither got any replies from Stack flow, the forum nor Firebase support. I have had to work around this problem using temporary solutions, but I want to solve it once and for all.
Whenever I run Firebase admin everything works except for Firebase admin database and my app crashes with the following error when I run npm start for my node backend

```
internal/crypto/sig.js:110
[0]   const ret = this[kHandle].sign(data, format, type, passphrase, rsaPadding,
[0]                             ^
[0]
[0] Error: error:25078067:DSO support routines:win32_load:could not load the shared library
[0]     at Sign.sign (internal/crypto/sig.js:110:29)
[0]     at Object.sign (C:\Users\black\Documents\Programming\Acumen-Developers\Web\Highway420\node_modules\jwa\index.js:152:45)
[0]     at Object.jwsSign [as sign] (C:\Users\black\Documents\Programming\Acumen-Developers\Web\Highway420\node_modules\jws\lib\sign-stream.js:32:24)
[0]     at Object.module.exports [as sign] (C:\Users\black\Documents\Programming\Acumen-Developers\Web\Highway420\node_modules\jsonwebtoken\sign.js:204:16)
[0]     at ServiceAccountCredential.createAuthJwt_ (C:\Users\black\Documents\Programming\Acumen-Developers\Web\Highway420\node_modules\firebase-admin\lib\credential\credential-internal.js:102:20)
[0]     at ServiceAccountCredential.getAccessToken (C:\Users\black\Documents\Programming\Acumen-Developers\Web\Highway420\node_modules\firebase-admin\lib\credential\credential-internal.js:75:26)
[0]     at FirebaseAppInternals.getToken (C:\Users\black\Documents\Programming\Acumen-Developers\Web\Highway420\node_modules\firebase-admin\lib\firebase-app.js:66:73)
[0]     at FirebaseAuthTokenProvider.getToken (C:\Users\black\Documents\Programming\Acumen-Developers\Web\Highway420\node_modules\firebase-admin\node_modules\@firebase\database\dist\index.node.cjs.js:14954:27)
[0]     at PersistentConnection.establishConnection_ (C:\Users\black\Documents\Programming\Acumen-Developers\Web\Highway420\node_modules\firebase-admin\node_modules\@firebase\database\dist\index.node.cjs.js:12163:18)
[0]     at Timeout._onTimeout (C:\Users\black\Documents\Programming\Acumen-Developers\Web\Highway420\node_modules\firebase-admin\node_modules\@firebase\database\dist\index.node.cjs.js:12064:19) {
[0]   opensslErrorStack: [
[0]     'error:0E076071:configuration file routines:module_run:unknown module name',
[0]     'error:0E07506E:configuration file routines:module_load_dso:error loading dso',
[0]     'error:25070067:DSO support routines:DSO_load:could not load the shared library'
[0]   ],
[0]   library: 'DSO support routines',
[0]   function: 'win32_load',
[0]   reason: 'could not load the shared library',
[0]   code: 'ERR_OSSL_DSO_COULD_NOT_LOAD_THE_SHARED_LIBRARY'
[0] }
```

I don't have jsonwebtoken installed myself in my node package, so I know it is not a problem on my part. I have searched the internet and done everything from deleting node_modules and package-lock.json and reinstalling with npm install to updating all packages. It also isn't a case of my GOOGLE_APPLICATION_CREDENTIALS not being found because like is said, admin auth, admin storage work but not admin database

  * Operating System version: Windows 10
  * Firebase SDK version: 7.24.0
  * Firebase Product: database
  * Node.js version: 14.15.4
  * NPM version: 6.14
Thank you for your help

**Comment by hiranya911** [comment]
This is a problem with your local crypto/OpenSSL set up. Seems to be a fairly a common issue on Windows systems based on some Google search hits:

https://stackoverflow.com/questions/65689482/node-error25078067dso-support-routineswin32-loadcould-not-load-the-shared-l
https://github.com/nodejs/help/issues/848 (somewhat old, but seems to be the same issue)
https://www.gitmemory.com/issue/OpenSC/libp11/298/526593658

I'll assign to the RTDB team to see if they have seen anything like this before. But I'd also advise you to check with Windows and OpenSSL communities for more specific instructions.

**Comment by ishowta** [comment]
I upgraded to Node 16.16.0 and it works.
Perhaps related to this issue. https://github.com/nodejs/node/discussions/43184#discussioncomment-3107873

**Comment by litehacker** [comment]
You can check for OpenSSL version to your NodeJS version compatibility [here](https://github.com/nodejs/TSC/blob/main/OpenSSL-Strategy.md)

**Comment by 6010110455** [comment]
@ishowta  Thank you, It works for me too.
