### ISSUE TITLE
TypeError: obj.hasOwnProperty is not a function at each

### ISSUE THREAD

**Issue by Setarsehari** [firebase/firebase-admin-node#1188]
I have a problem sending an argument

***schema***

      extend type AdminMutation {
        addQuestions(questions: [QuestionsInput!]!): FailureSuccess!
      }
      

***request***

    mutation {
      admin {
        addQuestions(
          questions: [
             {
              question: "what will we see in the console ?"
              answers: ["1 1", "undefined undefined", "undefined 1", "Error"]
              correctAnswer: "undefined 1"
              img: "/js/1.png"
              point: 6
            }
          ]
        )
      }
    }

when i try to save question i get error

***resolvers***

    7    async function addQuestions(
    8      { questions }: { questions: [QuestionsInput] },
    9      { db }: Context
    10    ) {
    11      try {
    12        await db.ref("/question").push({
    13          date: moment().format("MMMM Do YYYY, h:mm:ss a"),
    14          questions,
    15        });
    16      } catch (error) {
    17        console.log(error);
    18      }
    19    }

  >TypeError: obj.hasOwnProperty is not a function
    at each (C:\Users\darkc\Desktop\🔥🔥🔥🔥\server\node_modules\firebase-admin\node_modules\@firebase\database\src\core\util\util.ts:416:13)
    at validateFirebaseData (C:\Users\darkc\Desktop\🔥🔥🔥🔥\server\node_modules\firebase-admin\node_modules\@firebase\database\src\core\util\validation.ts:185:5)
    at C:\Users\darkc\Desktop\🔥🔥🔥🔥\server\node_modules\firebase-admin\node_modules\@firebase\database\src\core\util\validation.ts:204:7    at each (C:\Users\darkc\Desktop\🔥🔥🔥🔥\server\node_modules\firebase-admin\node_modules\@firebase\database\src\core\util\util.ts:417:7)
    at validateFirebaseData (C:\Users\darkc\Desktop\🔥🔥🔥🔥\server\node_modules\firebase-admin\node_modules\@firebase\database\src\core\util\validation.ts:185:5)
    at C:\Users\darkc\Desktop\🔥🔥🔥🔥\server\node_modules\firebase-admin\node_modules\@firebase\database\src\core\util\validation.ts:204:7    at each (C:\Users\darkc\Desktop\🔥🔥🔥🔥\server\node_modules\firebase-admin\node_modules\@firebase\database\src\core\util\util.ts:417:7)
    at validateFirebaseData (C:\Users\darkc\Desktop\🔥🔥🔥🔥\server\node_modules\firebase-admin\node_modules\@firebase\database\src\core\util\validation.ts:185:5)
    at validateFirebaseDataArg (C:\Users\darkc\Desktop\🔥🔥🔥🔥\server\node_modules\firebase-admin\node_modules\@firebase\database\src\core\util\validation.ts:122:3)
    at Reference.push (C:\Users\darkc\Desktop\🔥🔥🔥🔥\server\node_modules\firebase-admin\node_modules\@firebase\database\src\api\Reference.ts:336:5)

How can I fix this error ?

**Comment by schmidt-sebastian** [comment]
@Setarsehari What version of the RTDB SDK are you using? Furthermore, it looks like you are building directly from source. Does this problem also exist if you are installing our NPM modules?

**Comment by hiranya911** [comment]
I'm going to close this since there hasn't been any feedback. We can reopen if there's new information.
