### ISSUE TITLE
[Firestore] Error trying to query data through firebase cloud functions.

### ISSUE THREAD

**Issue by Giulio64** [firebase/firebase-admin-node#1200]
### [ENV]

  * Operating System version: MacOS Catalina
  * Firebase SDK version: 9.5.0
  * Firebase Product: Firestore
  * Node.js version: v14.15.5
  * NPM version: 6.14.11

### [PROBLEM]:

I have the following data structure 

```
    Quotation:{
       QUOTATION_ID:{
         creation:...
         exiperation:...
         performanceID:...
       }
    }

    QuotationRow:{
       QUOTATION_ID:{
         ROW_ID:{ 
            description:"",
            subTotal:10.0
         }
       }
    }
```

I want to query and format in single response these records through the following function:

```
/**
   * Returns a graph containing all the quoations.
   * @return {Object} [Containing the response]
   */
  getQuotationGraphAsync() {
    return new Promise((res, rej) => {
      const quotationRequest = admin.database().ref("Quotation").once("value");
      const rowsRequest = admin.database().ref("QuotationRow").once("value");

      const requests = [];
      requests.push(quotationRequest);
      requests.push(rowsRequest);

      Promise.all(requests)
          .then((responses) => {
            System.prototype.writeLog({quotationResponses: responses});
            const quotations = responses[0].val() !== null ? responses[0].val() : {};
            const rows = responses[1].val() !== null ? responses[1].val() : {};

            const response = {};

            for (const quotationID in quotations) {
              const quotation = quotation[quotationID];
              quotation.rows = rows[quotationID];
              response[quotationID] = quotation;
            }

            return res({code: 200, data: response});
          });
    });
  }
```

The problem is that the function crashes when I try to query the quotations and rows with the following error:
```
TypeError: this.indexMap_.get is not a function
    at Object.ChildrenNode.resolveIndex_ (/workspace/node_modules/@firebase/database/dist/index.node.cjs.js:3902:35)
    at Object.ChildrenNode.forEachChild (/workspace/node_modules/@firebase/database/dist/index.node.cjs.js:3745:24)
    at Object.ChildrenNode.val (/workspace/node_modules/@firebase/database/dist/index.node.cjs.js:3629:14)
    at Object.DataSnapshot.exportVal (/workspace/node_modules/@firebase/database/dist/index.node.cjs.js:4268:27)
    at Object.DataSnapshot.toJSON (/workspace/node_modules/@firebase/database/dist/index.node.cjs.js:4275:21)
    at JSON.stringify (<anonymous>)
    at write (/workspace/node_modules/firebase-functions/lib/logger.js:39:84)
    at Object.log (/workspace/node_modules/firebase-functions/lib/logger.js:72:5)
    at Object.writeLog (/workspace/System/System.js:123:22) 
```

### [STEP TO REPRODUCE]:
*Deploy the functions
*Use the attached Insomnia project to fire the getUsers function.

**Comment by hiranya911** [comment]
I think it because you're trying to JSON serialize a snapshot value:

```
System.prototype.writeLog({quotationResponses: responses});
```

Notice that the error stacktrace has originated in the `logger` module. Try running your code without the above line.

**Comment by Giulio64** [comment]
Thanks, that fixed the issue, you can close.
