### ISSUE TITLE
@grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0

### ISSUE THREAD

**Issue by radvansky-tomas** [firebase/firebase-admin-node#1228]
Device: M1 Apple

Node installed using NVM - 15.14.0 - native ARM supported version

Running npm run test -> running jest fails with:

```
lib/common/services/registration-service.test.js
  ● Test suite failed to run

    @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0

      at Object.<anonymous> (node_modules/@grpc/grpc-js/src/index.ts:71:9)
      at Object.<anonymous> (node_modules/google-gax/src/index.ts:17:1)
```

All worked fine couple days ago

**Comment by radvansky-tomas** [comment]
Maybe similar to https://stackoverflow.com/questions/65462255/firebase-admin-sdk-on-apple-silicon-not-working

**Comment by radvansky-tomas** [comment]
resolved: https://github.com/facebook/jest/issues/6127
