### ISSUE TITLE
Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET

### ISSUE THREAD

**Issue by bosung90** [firebase/firebase-admin-node#1364]
I got this error on Firebase Functions with firestore.document('...').onUpdate(...
while trying to call .set(`newData`, {merge: true})

The document was never updated with the `newData`

This happens occasionally (once every 200~1000 triggers or so)

Running this on firebase functions
Node@14
firebase-functions@3.14.1
firebase-admin@9.10.0

```
Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: read ECONNRESET
    at Object.callErrorFromStatus (/workspace/node_modules/firebase-admin/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/firebase-admin/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/workspace/node_modules/firebase-admin/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/workspace/node_modules/firebase-admin/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /workspace/node_modules/firebase-admin/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11) 
```

**Comment by bosung90** [comment]
@schmidt-sebastian Do you think you can take a look please?

**Comment by ttloves2** [comment]
Cuz someone explain alittle better?

Sent from my iPhone

On Jul 8, 2021, at 9:57 PM, Google Open Source Bot ***@***.***> wrote:

﻿
I found a few problems with this issue:

I couldn't figure out how to label this issue, so I've labeled it for a human to triage. Hang tight.
This issue does not seem to follow the issue template. Make sure you provide all the required information.

**Comment by schmidt-sebastian** [comment]
This is a duplicate of https://github.com/googleapis/nodejs-firestore/issues/1023. Let's discuss over there.
