### ISSUE TITLE
[Firestore] Error: 4 DEADLINE_EXCEEDED: Deadline exceeded

### ISSUE THREAD

**Issue by JFGHT** [firebase/firebase-admin-node#1396]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Ubuntu 21_04
  * Firebase SDK version: firebase-admin@9.6.0
  * Firebase Product: Firestore
  * Node.js version: v14.16.1
  * NPM version: Yarn 1.22.5

#### Steps to reproduce:

I am trying to dump into Firestore thousands of documents into collections and subcollections via batch. I am using this class
https://github.com/Mikkelet/firebase-helpers/blob/master/batch_bulk.ts to help myself commiting in a parallelized way all the files I need.

As I can see in my own logs, there is no problem uploading "little" bunchs of data like:
> Committing 11754 changes

But when the hardcore part comes, it fails:
> Committing 747988 changes

```
(node:13203) UnhandledPromiseRejectionWarning: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded
    at Object.callErrorFromStatus (/home/x/apps/y/z/functions/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/home/x/apps/y/z/functions/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/home/x/apps/y/z/functions/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/home/x/apps/y/z/functions/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /home/x/apps/y/z/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
Caused by: Error
    at WriteBatch.commit (/home/x/apps/y/z/functions/node_modules/@google-cloud/firestore/build/src/write-batch.js:413:23)
    at /home/x/apps/y/z/functions/lib/lib/batches.js:76:70
    at Array.forEach (<anonymous>)
    at BatchInstance.<anonymous> (/home/x/apps/y/z/functions/lib/lib/batches.js:76:35)
    at Generator.next (<anonymous>)
    at /home/x/apps/y/z/functions/lib/lib/batches.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/x/apps/y/z/functions/lib/lib/batches.js:4:12)
    at BatchInstance.commit (/home/x/apps/y/z/functions/lib/lib/batches.js:61:16)
    at /home/x/apps/y/z/functions/lib/etl.js:510:37
```

This is not inside a Cloud Function (just executing it via local node) and it fails in prod and also in the emulator.

```ts
/**
 * Prod config
 */
initializeApp({
  credential: credential.cert(require('../service-account.json')),
  databaseURL: 'https://x.firebaseio.com',
});

/**
 * 
 * test config
 */
// process.env.FIRESTORE_EMULATOR_HOST = 'localhost:8081';

// initializeApp({
//   projectId: 'x',
// });
```

**Comment by lahirumaramba** [comment]
A common reason for this to happen is when you don't await on an async function or forget to return a promise to handle it properly. How do you use the class in your script?

**Comment by JFGHT** [comment]
Yeah, I fixed that one up but that's not the problem.

Maybe I am reaching the [Maximum Writes per second](https://firebase.google.com/docs/firestore/quotas#writes_and_transactions)?
747988 / 500 = 1496 parallel batches of 500.
How could I measure the writes per second that its going under the hood?

**Comment by schmidt-sebastian** [comment]
You are likely hitting some of our limits. There are limits regarding maximum writes per second, as well as other limits that depend on your index layout (see https://cloud.google.com/firestore/docs/best-practices#hotspots) and possible your project as a whole (https://firebase.google.com/docs/firestore/best-practices#ramping_up_traffic).

The WriteBatch API does not attempt to retry these failures as we do not know whether your writes are idempotent. I would advise you to throttle your write speed or to migrate your code to BulkWriter (https://googleapis.dev/nodejs/firestore/latest/Firestore_.html#bulkWriter), which handles these writes loads for your and inserts backoff as appropriate.
