### ISSUE TITLE
Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token.

### ISSUE THREAD

**Issue by vladimirteddy** [firebase/firebase-admin-node#1431]
I login through firebase and get the person info with token through firebase admin. But after a while of logging in and using, all of a sudden my user got kicked out and then I logged back in and got the following error:
FirebaseAppError: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request: getaddrinfo EMFILE accounts.google.com. Error code: EMFILE".
    at FirebaseAppError.FirebaseError [as constructor] (/app/node_modules/firebase-admin/lib/utils/error.js:44:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/app/node_modules/firebase-admin/lib/utils/error.js:90:28)
    at new FirebaseAppError (/app/node_modules/firebase-admin/lib/utils/error.js:125:28)
    at /app/node_modules/firebase-admin/lib/firebase-app.js:86:19
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FirebaseService.getUserFirebase (/app/dist/firebase/firebase.service.js:44:20)
    at async FirebaseService.authenticateFirebase (/app/dist/firebase/firebase.service.js:33:20)
    at async AuthController.authenticate (/app/dist/auth/controllers/auth.controller.js:51:38) {
  errorInfo: {
    code: 'app/invalid-credential',
    message: 'Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request: getaddrinfo EMFILE accounts.google.com. Error code: EMFILE".'
  },
  codePrefix: 'app'
}
Please help me.

**Comment by hiranya911** [comment]
Your process is leaking open file handles and hitting the system-level limit: https://blog.izs.me/2013/07/wtf-is-emfile-and-why-does-it-happen-to-me/

You will have to either raise the limit, or debug and figure out how your application is leaking file handles.
