### ISSUE TITLE
Realtime Database Stuck

### ISSUE THREAD

**Issue by mr-zxy** [firebase/firebase-admin-node#1480]
When I use firebase realtime database data, I use set to add data, but I can't add it all the time. The Promise object can be printed out and returned, but. Then and. Catch never return data. Do you have any ideas to help analyze? There is no problem with curd when using firestore database.

**Comment by schmidt-sebastian** [comment]
Hello! Thanks for filing this issue. We won't be able to help unless you can provide us with logs or a reproduction though. Is that something you can do?

**Comment by milo-** [comment]
Hi @schmidt-sebastian, we're also seeing calls to realtime DB hang when using with the emulator. We're using firebase-admin 10.0.0 and firebase-tools 9.23.0.

The RDB emulator is running, and function triggers are working correctly. However reads from our testsuite to RDB using firbease-admin hang. We've enabled logging and are seeing the error:
```

console.log
    p:0: Making a connection attempt

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)

  console.log
    getToken() completed. Creating connection.

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)

  console.log
    c:0:9: Connection created

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)

  console.log
    c:0:9:0 Websocket connecting to ws://localhost:9000/.ws?v=5&ns=

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)

  console.log
    c:0:9:0 WebSocket error.  Closing connection.

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)

  console.log
    c:0:9:0 Error during WebSocket handshake: Unexpected response code: 403

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)

  console.log
    c:0:9:0 WebSocket is closing itself

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)

  console.log
    c:0:9: Realtime connection failed.

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)

  console.log
    c:0:9: Closing realtime connection.

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)

  console.log
    c:0:9: Shutting down all connections

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)

  console.log
    p:0: data client disconnected

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)

  console.log
    p:0: Trying to reconnect in 1284.6646720609474ms

      at log (node_modules/@firebase/database/dist/index.standalone.js:313:9)
```

Hope that helps, let me know if you need more info.

**Comment by schmidt-sebastian** [comment]
@jsdt Can you take a look?
