### ISSUE TITLE
Firebase storage not respecting FIREBASE_STORAGE_EMULATOR_HOST env var in some cases

### ISSUE THREAD

**Issue by vajahath** [firebase/firebase-admin-node#1562]
### Step 2: Describe your environment

  * Operating System version: Ubuntu 21
  * Firebase SDK version: ^10.0.2
  * Firebase Product: storage
  * Node.js version: 16
  * NPM version: 8

### Step 3: Describe the problem
Even though I set `FIREBASE_STORAGE_EMULATOR_HOST=localhost:9199`, the `bucket.file('file').save(<buffer>)` is calling `0.0.0.0:9199` instead of the specified `localhost:9199`. Is this expected?

In usual environments, this issue may not pop up because localhost and 0.0.0.0 points to the same network. But in container environments _(like in [Github Actions Service Containers](https://docs.github.com/en/actions/using-containerized-services/about-service-containers) where I run emulator as a service container so that I can run tests against it)_ this issue is causing the admin sdk to not connect to storage emulator at all. Giving me:
```js
await Bucket.file("test-folder/my-file.jpg").save(imageBugger);
```
```sh
$ export FIREBASE_STORAGE_EMULATOR_HOST=firebase_emulator:9199 # container environment
```
```
     FetchError: request to http://0.0.0.0:9199/upload/storage/v1/b/demo-friendly-octopus-u4st7gxr8.appspot.com/o?name=15498def-9a0e-427b-9b30-46be44b08789_b_demo-friendly-octopus-u4st7gxr8.appspot.com_o_sh3kxCD%2F50.jpeg&uploadType=resumable&upload_id=15498def-9a0e-427b-9b30-46be44b08789 failed, reason: connect ECONNREFUSED 0.0.0.0:9199
      at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1491:11)
      at ClientRequest.emit (node:events:402:35)
      at Socket.socketErrorListener (node:_http_client:447:9)
      at Socket.emit (node:events:390:28)
      at emitErrorNT (node:internal/streams/destroy:157:8)
      at emitErrorCloseNT (node:internal/streams/destroy:122:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I checked into the issue by adding console in `node_modules/node-fetch/lib/index.js`, where I found the `bucket.file().save()` calls the `node-fetch` twice each time with different hosts. First with host `localhost` and second time with `0.0.0.0`. Is this expected?
Here is the relevant trace logs
```
Trace: {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: 'localhost:9199', 👈👈
  port: '9199',
  hostname: 'localhost',
  hash: null,
  search: '?name=test-folder%2Fmy-file.jpg&uploadType=resumable',
  query: 'name=test-folder%2Fmy-file.jpg&uploadType=resumable',
  pathname: '/upload/storage/v1/b/demo-my-bucket/o',
  path: '/upload/storage/v1/b/demo-my-bucket/o?name=test-folder%2Fmy-file.jpg&uploadType=resumable',
  href: 'http://localhost:9199/upload/storage/v1/b/demo-my-bucket/o?name=test-folder%2Fmy-file.jpg&uploadType=resumable',
  method: 'POST',
  // ...
}
    at /home/vaju/Documents/firebase-issue/node_modules/node-fetch/lib/index.js:1469:11
    at new Promise (<anonymous>)
    at fetch (/home/vaju/Documents/firebase-issue/node_modules/node-fetch/lib/index.js:1437:9)
    at Gaxios._defaultAdapter (/home/vaju/Documents/firebase-issue/node_modules/gaxios/build/src/gaxios.js:111:28)
    at Gaxios._request (/home/vaju/Documents/firebase-issue/node_modules/gaxios/build/src/gaxios.js:126:49)
    at Gaxios.request (/home/vaju/Documents/firebase-issue/node_modules/gaxios/build/src/gaxios.js:107:21)
    at Object.request (/home/vaju/Documents/firebase-issue/node_modules/gaxios/build/src/index.js:30:29)
    at Upload.makeRequest (/home/vaju/Documents/firebase-issue/node_modules/@google-cloud/storage/build/src/gcs-resumable-upload/index.js:626:43)
    at retry.retries (/home/vaju/Documents/firebase-issue/node_modules/@google-cloud/storage/build/src/gcs-resumable-upload/index.js:333:40)
    at RetryOperation.runAttempt [as _fn] (/home/vaju/Documents/firebase-issue/node_modules/async-retry/lib/index.js:42:15)
Trace: {
  protocol: 'http:',
  slashes: true,
  auth: null,
  host: '0.0.0.0:9199', 👈👈
  port: '9199',
  hostname: '0.0.0.0',
  hash: null,
  search: '?name=7d9f2762-31e9-4495-ab85-01d300312a80_b_demo-my-bucket_o_test-folder%2Fmy-file.jpg&uploadType=resumable&upload_id=7d9f2762-31e9-4495-ab85-01d300312a80',
  query: 'name=7d9f2762-31e9-4495-ab85-01d300312a80_b_demo-my-bucket_o_test-folder%2Fmy-file.jpg&uploadType=resumable&upload_id=7d9f2762-31e9-4495-ab85-01d300312a80',
  pathname: '/upload/storage/v1/b/demo-my-bucket/o',
  path: '/upload/storage/v1/b/demo-my-bucket/o?name=7d9f2762-31e9-4495-ab85-01d300312a80_b_demo-my-bucket_o_test-folder%2Fmy-file.jpg&uploadType=resumable&upload_id=7d9f2762-31e9-4495-ab85-01d300312a80',
  href: 'http://0.0.0.0:9199/upload/storage/v1/b/demo-my-bucket/o?name=7d9f2762-31e9-4495-ab85-01d300312a80_b_demo-my-bucket_o_test-folder%2Fmy-file.jpg&uploadType=resumable&upload_id=7d9f2762-31e9-4495-ab85-01d300312a80',
  method: 'PUT',
  headers: [Object: null prototype] {
    'Content-Range': [ 'bytes 0-*/*' ],
    Accept: [ 'application/json' ],
    'User-Agent': [ 'node-fetch/1.0 (+https://github.com/bitinn/node-fetch)' ],
    'Accept-Encoding': [ 'gzip,deflate' ],
    Connection: [ 'close' ]
  },
  agent: undefined
}
    at /home/vaju/Documents/firebase-issue/node_modules/node-fetch/lib/index.js:1469:11
    at new Promise (<anonymous>)
    at fetch (/home/vaju/Documents/firebase-issue/node_modules/node-fetch/lib/index.js:1437:9)
    at Gaxios._defaultAdapter (/home/vaju/Documents/firebase-issue/node_modules/gaxios/build/src/gaxios.js:111:28)
    at Gaxios._request (/home/vaju/Documents/firebase-issue/node_modules/gaxios/build/src/gaxios.js:126:49)
    at Gaxios.request (/home/vaju/Documents/firebase-issue/node_modules/gaxios/build/src/gaxios.js:107:21)
    at Object.request (/home/vaju/Documents/firebase-issue/node_modules/gaxios/build/src/index.js:30:29)
    at Upload.makeRequestStream (/home/vaju/Documents/firebase-issue/node_modules/@google-cloud/storage/build/src/gcs-resumable-upload/index.js:644:43)
    at Upload.startUploading (/home/vaju/Documents/firebase-issue/node_modules/@google-cloud/storage/build/src/gcs-resumable-upload/index.js:466:37)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
#### Steps to reproduce:
(The following file works with localhost-ed emulator. But please see the logs from node-fetch)
`save.mjs`
```js
process.env.FIREBASE_STORAGE_EMULATOR_HOST ??= "localhost:9199";
process.env.GCLOUD_PROJECT ??= "demo-my-project";
process.env.FIREBASE_CONFIG ??= JSON.stringify({
  storageBucket: "demo-my-bucket",
});
console.log(`FIREBASE_STORAGE_EMULATOR_HOST: ${process.env.FIREBASE_STORAGE_EMULATOR_HOST}`);
console.log(`GCLOUD_PROJECT: ${process.env.GCLOUD_PROJECT}`);
console.log(`FIREBASE_CONFIG: ${process.env.FIREBASE_CONFIG}`);

import * as admin from "firebase-admin/app";
import { getStorage } from "firebase-admin/storage";
import { readFile } from "node:fs/promises";

const app = admin.initializeApp();
const Bucket = getStorage(app).bucket();

const imageBugger = await readFile(new URL("./save.mjs", import.meta.url));

await Bucket.file("test-folder/my-file.txt").save(imageBugger);
```
edit `node_modules/node-fetch/lib/index.js`
```js
                // ...
		// send request
		const req = send(options);
		console.trace(options);  👈👈
		let reqTimeout;
                // ...
```
We get the logs as shown in the previous section. Is this expected behaviour?

**Comment by vajahath** [comment]
I got a change to look into this a bit. **Not sure if my findings are correct**.

I added some debuggers around:
https://github.com/googleapis/nodejs-storage/blob/f5fab17baa7767d6dcd9da6768cd6cc6ef87a739/src/gcs-resumable-upload/index.ts#L630
![Screenshot from 2022-01-27 21-44-41](https://user-images.githubusercontent.com/12165822/151398768-65852b4a-50bb-400a-95b4-a52c14e78a63.png)

The `bucket.save()` calls the emulator 2 times
- on the first try, with correct host (as specified in the FIREBASE_STORAGE_EMULATOR_HOST, in my case, `localhost`), the emulator responds with 
```
res.headers.location='http://0.0.0.0:9199/upload/storage/v1/b/...'
                            ^^^^^^^
``` 
- next call to emulator is made with this gotten url, `http://0.0.0.0:9199/upload/storage/v1/b/...` resulting in error in container environments.

### Applying my humble findings back to the issue to see how things fit

So in container environment,
- firebase emulator is one container, say `firebase`
- app is another container, say  `app`

Thus, in app container I set `FIREBASE_STORAGE_EMULATOR_HOST=firebase:9199`. When I run the app,
- sdk make the first call with `firebase:9199`, giving a `response.headers.location=http://0.0.0.0:9199/..`
- next call is made with the gotten 0.0.0.0 host giving me the shown error in the issue.
```
     FetchError: request to http://0.0.0.0:9199/upload/storage/v1/b/..
       ... reason: connect ECONNREFUSED 0.0.0.0:9199
```
because 0.0.0.0 is not firebase emulator. 

### Checking again

I use `firebase.json`:
```json
{
  "firestore": {
    "rules": "firestore.rules",
    "indexes": "firestore.indexes.json"
  },
  "functions": {
    "predeploy": [
      "npm --prefix \"$RESOURCE_DIR\" run lint",
      "npm --prefix \"$RESOURCE_DIR\" run build"
    ]
  },
  "storage": {
    "rules": "storage.rules"
  },
  "emulators": {
    "auth": {
      "port": 9099,
      "host": "0.0.0.0"
    },
    "functions": {
      "port": 5001,
      "host": "0.0.0.0"
    },
    "firestore": {
      "port": 8080,
      "host": "0.0.0.0"
    },
    "storage": {
      "port": 9199,
      "host": "0.0.0.0"
    },
    "ui": {
      "enabled": true,
      "host": "0.0.0.0"
    }
  }
}
```
Note that I've to use 0.0.0.0 to make the emulators reachable from outside the container.
To validate my findings, I replaced these 0.0.0.0 with `firebase` so that it look like following.
```jsonc
{
 // ...
  "emulators": {
    "auth": {
      "port": 9099,
      "host": "firebase"
    },
    "functions": {
      "port": 5001,
      "host": "firebase"
    },
    "firestore": {
      "port": 8080,
      "host": "firebase"
    },
    "storage": {
      "port": 9199,
      "host": "firebase"
    },
    "ui": {
      "enabled": true,
      "host": "firebase"
    }
  }
}
```
When I ran the app, it was success. My assumption is
- when sdk first made the call with `${FIREBASE_STORAGE_EMULATOR_HOST}` emulator returned the response with
```js
response.headers.location=`${<firebase.json>.emulators.storage.<host and port>}` // which is "firebase" (same as FIREBASE_STORAGE_EMULATOR_HOST)
```
- second call made with the gotten `firebase` host, which happens to be correct by chance.

Thus the execution went ok.
I think both calls should respect `${FIREBASE_STORAGE_EMULATOR_HOST}`. But that's just me saying, without seeing the big picture.
I just thought I'll add my findings here..

**Comment by lahirumaramba** [comment]
Hi @vajahath thank you for filing this issue and sharing your findings with us! We appreciate it.
@firebase/firebase-tools team have identified the issue and currently working on a fix.

**Comment by maelp** [comment]
I have the same issue, although I'm using the latest firebase-admin and firebase-tools, any idea?

**Comment by maelp** [comment]
and for me, replacing the "0.0.0.0" in the firebase.json does not change the issue
