### ISSUE TITLE
Exception during save data to firestore from cloud function

### ISSUE THREAD

**Issue by mpilalex** [firebase/firebase-admin-node#165]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Cloud functions
  * Firebase SDK version: 5.5.1
  * Library version: 5.5.1
  * Firebase Product: cloud functions, firestore (auth, database, storage, etc)

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

From time to time i see an exceptions into firestore cloud functions log

1. Error: Stream removed
    at ClientReadableStream._emitStatusIfDone (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client.js:255:19)
    at ClientReadableStream._receiveStatus (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client.js:233:8)
    at /user_code/node_modules/firebase-admin/node_modules/grpc/src/client.js:705:12

2.  Error: Stream removed
    at /user_code/node_modules/firebase-admin/node_modules/grpc/src/client.js:554:15
  code: 2,
  metadata: Metadata { _internal_repr: {} },
  note: 'Exception occurred in retry method that was not classified as transient'

**Comment by hiranya911** [comment]
Firestore and Functions teams have been investigating this. See https://groups.google.com/forum/#!msg/firebase-talk/oza-JZMtXlo/DpFGz9BHCQAJ for the ongoing discussion. Stay tuned for an update.
