### ISSUE TITLE
FirebaseAppError: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request: connect ETIMEDOUT 172.217.163.45:443.".

### ISSUE THREAD

**Issue by Neo42** [firebase/firebase-admin-node#1724]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Monterey v12.3.1
  * Firebase SDK version: firebase-admin ^8.13.0; firebase ^3.5.1
  * Firebase Product: auth (auth, database, storage, etc)
  * Node.js version: v14.19.3
  * NPM version: v8.10.0

#### Steps to reproduce:

I was using a proxy with firebase-admin (because I'm in China and have to use a proxy to access Google's services like Firebase). My proxy is `http://127.0.0.1:8001`

After that, I logged in to firebase using firebase-tools. 

And then here is the npm command I was trying to run:

```
"custom-token": "NODE_ENV=production node ./getCustomTokenUrl",
```

```bash
npm run custom-token
```

It was supposed to go through the firebase authentication, get a user's email and print out the uid in the terminal (See the code below). But, instead, it just hung there for a long time and threw an error like the below.

```bash
▲ /// npm run custom-token

> NODE_ENV=production node ./getCustomTokenUrl

Browserslist: caniuse-lite is outdated. Please run next command `npm update`

FirebaseAppError: Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request: connect ETIMEDOUT 172.217.163.45:443.".
    at FirebaseAppError.FirebaseError [as constructor] (/Users/hao/Code/Backend/scripts/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/Users/hao/Code/Backend/scripts/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseAppError (/Users/hao/Code/Backend/scripts/node_modules/firebase-admin/lib/utils/error.js:123:28)
    at /Users/hao/Code/Backend/scripts/node_modules/firebase-admin/lib/firebase-app.js:121:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errorInfo: {
    code: 'app/invalid-credential',
    message: 'Credential implementation provided to initializeApp() via the "credential" property failed to fetch a valid Google OAuth2 access token with the following error: "Error fetching access token: Error while making request: connect ETIMEDOUT 172.217.163.45:443.".'
  },
  codePrefix: 'app'
}
```

I wonder if it has something to do with the proxy I use.

#### Relevant Code:

```js
// scripts/getCustomTokenUrl/app/index.js
import firebase from 'firebase-admin';
import { FIREBASE_CONFIG } from '../config';

firebase.initializeApp(FIREBASE_CONFIG);

export const getAppOwnerUid = email =>
  new Promise((resolve, reject) =>
    firebase
      .auth()
      .getUserByEmail(email)
      .then(userRecord => resolve(userRecord.toJSON().uid))
      .catch(reject),
  );
/**
 * Generates login token for the user
 * @param {string} appname
 * @param {string} email
 * @returns {promise}
 */
export const generateLoginToken = email =>
  new Promise((resolve, reject) => {
    if (!email) {
      reject('INVALID_REQUEST');
    }

    firebase
      .auth()
      .createCustomToken(email)
      .then(resolve)
      .catch(reject);
  });

const getCustomTokenUrl = async () => {
  try {
    const email = '***@***.com'; // hard-coded target user's email address
    const uid = await getAppOwnerUid(email);
    const token = await generateLoginToken(uid);
    const domainLocal = 'https://localhost:3005';
    const domainStaging = 'https://*****-staging.firebaseapp.com';
    const domainProd = 'https://create.*****.com';
    const path = '/integrations/login?customtoken=';

    console.log(`${domainLocal}${path}${token}`);
    console.log(`${domainStaging}${path}${token}`);
    console.log(`${domainProd}${path}${token}`);
    process.exit(0);
  } catch (err) {
    console.log(err);
    process.exit(0);
  }
};

getCustomTokenUrl();
```

```js
// ../config
import path from 'path';
import fs from 'fs';
import firebase from 'firebase-admin';

const env = process.env.NODE_ENV;

function getDatabaseUrl() {
  switch (env) {
    case 'staging':
      return 'https://*****.firebaseio.com/';
    case 'production':
      return 'https://*****.firebaseio.com/';
    default:
      return 'https://*****.firebaseio.com/';
  }
}

const JSONfile = fs.readFileSync(path.join(__dirname, `/${env}.json`), 'utf8');

const serviceAccount = JSON.parse(JSONfile);

export const FIREBASE_CONFIG = {
  credential: firebase.credential.cert(serviceAccount),
  databaseURL: getDatabaseUrl(),
};
```

**Comment by Neo42** [comment]
I was able to solve this with the following code.

```js
// ../config

import httpProxyAgent from 'https-proxy-agent';

const httpAgent = new httpProxyAgent('http://127.0.0.1:8001/');

// config passed into admin.initializeApp()
export const FIREBASE_CONFIG = {
  credential: firebase.credential.cert(serviceAccount, httpAgent),
  databaseURL: getDatabaseUrl(),
  httpAgent,
};
```

**Comment by garrett-wombat** [comment]
I had this same issue come up. The fix for me was to revert a `firebase-tools` update from `10.8` to `10.9.2` back to `10.8`
