### ISSUE TITLE
Error: error:25066067:DSO support routines:dlfcn_load:could not load the shared library

### ISSUE THREAD

**Issue by miladezzat** [firebase/firebase-admin-node#1755]
```
Error: error:25066067:DSO support routines:dlfcn_load:could not load the shared library
    at Sign.sign (node:internal/crypto/sig:131:29)
    at Object.sign (/media/milad/0063baf0-8e25-49ab-9434-8d20c8d89afe/milad/shariiky/api/node_modules/jwa/index.js:152:45)
    at Object.jwsSign [as sign] (/media/milad/0063baf0-8e25-49ab-9434-8d20c8d89afe/milad/shariiky/api/node_modules/jws/lib/sign-stream.js:32:24)
    at Object.module.exports [as sign] (/media/milad/0063baf0-8e25-49ab-9434-8d20c8d89afe/milad/shariiky/api/node_modules/jsonwebtoken/sign.js:204:16)
    at ServiceAccountCredential.createAuthJwt_ (/media/milad/0063baf0-8e25-49ab-9434-8d20c8d89afe/milad/shariiky/api/node_modules/firebase-admin/lib/app/credential-internal.js:105:20)
    at ServiceAccountCredential.getAccessToken (/media/milad/0063baf0-8e25-49ab-9434-8d20c8d89afe/milad/shariiky/api/node_modules/firebase-admin/lib/app/credential-internal.js:77:26)
    at FirebaseAppInternals.refreshToken (/media/milad/0063baf0-8e25-49ab-9434-8d20c8d89afe/milad/shariiky/api/node_modules/firebase-admin/lib/app/firebase-app.js:47:49)
    at FirebaseAppInternals.getToken (/media/milad/0063baf0-8e25-49ab-9434-8d20c8d89afe/milad/shariiky/api/node_modules/firebase-admin/lib/app/firebase-app.js:38:25)
    at AuthorizedHttpClient.getToken (/media/milad/0063baf0-8e25-49ab-9434-8d20c8d89afe/milad/shariiky/api/node_modules/firebase-admin/lib/utils/api-request.js:679:34)
    at AuthorizedHttpClient.send (/media/milad/0063baf0-8e25-49ab-9434-8d20c8d89afe/milad/shariiky/api/node_modules/firebase-admin/lib/utils/api-request.js:667:21) {
  opensslErrorStack: [
    'error:0E076071:configuration file routines:module_run:unknown module name',
    'error:0E07506E:configuration file routines:module_load_dso:error loading dso',
    'error:25070067:DSO support routines:DSO_load:could not load the shared library'
  ],
  library: 'DSO support routines',
  function: 'dlfcn_load',
  reason: 'could not load the shared library',
  code: 'ERR_OSSL_DSO_COULD_NOT_LOAD_THE_SHARED_LIBRARY'
}
```

OS: Ubuntu 22.4
firebase-admin: 10.2.0

**Comment by lahirumaramba** [comment]
Could be related to this https://github.com/auth0/node-jsonwebtoken/issues/826#issuecomment-1125607622
Looks like for openssl v3 you need to use node v18. There is a workaround mentioned in the link above.

**Comment by lahirumaramba** [comment]
Thanks @miladezzat ! I will convert this to a discussion as it might help others having the same issue.
