### ISSUE TITLE
[Firestore] Timestamp.fromDate(date) broken

### ISSUE THREAD

**Issue by fabienpatou** [firebase/firebase-admin-node#1793]
- Operating System version: N/A
- Firebase (**admin**) SDK version: 11.0.0
- Firebase Product: Firestore
- Node.js version: 16
- NPM version: 8.9.0

Timestamp.fromDate(date) is broken with following error:

>  TypeError: Cannot read properties of undefined (reading 'fromDate')
>      at dateToTimestamp (/Users/fabienpatou/dev/plato-backend-firebase/functions/lib/utils/utils.js:129:61)
>      at /Users/fabienpatou/dev/plato-backend-firebase/functions/lib/B2BFunctions/Agenda/rejectCall.js:67:52
>      at processTicksAndRejections (node:internal/process/task_queues:96:5)
>      at async /Users/fabienpatou/dev/plato-backend-firebase/functions/node_modules/firebase-functions/lib/common/providers/https.js:407:26
>      at async runFunction (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:564:9)
>      at async runHTTPS (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:590:5)
>      at async handler (/usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:510:17)

**Comment by fabienpatou** [comment]
Thanks @lahirumaramba, it's working !

The following is not working:
`import * as admin from "firebase-admin";
admin.firestore.Timestamp.fromDate(date);`
