### ISSUE TITLE
[FR] Support Edge and Deno runtime

### ISSUE THREAD

**Issue by oreqizer** [firebase/firebase-admin-node#1801]
**Is your feature request related to a problem? Please describe.**

https://nextjs.org/docs/api-reference/edge-runtime

I'd like to use `firebase-admin` in an Edge environment and Deno. The package currently uses Node-specific APIs though, making that impossible.

**Describe the solution you'd like**

Would be awesome to support the Edge/Deno runtime, e.g. via `firebase-admin/common`.

**Comment by lahirumaramba** [comment]
Duplicate of #1307

**Comment by akauppi** [comment]
@oreqizer This repo is open source. Do you think forking this repo and making `firebase-admin-deno` with the necessary changes is a possibility?

Disclaimer: I’m not a Deno user, and don’t suggest to contribute. It would be an interesting thing to follow, though…

**Comment by oreqizer** [comment]
@akauppi it definitely would be to some extent, depending on related dependencies. out of my time capacity to gauge/attempt though

**Comment by maccman** [comment]
We'd love to see nextjs edge support.

**Comment by Moe03** [comment]
Hey is there any progress with this PR?

**Comment by m3hari** [comment]
Using the rest API was my workaround see the story https://m3hari.medium.com/firebase-database-using-rest-api-3b4c8982164e

**Comment by 0x80** [comment]
@m3hari the admin package does more than that. For example, I'd like to decode a firebase id token and get custom claims from it.

**Comment by scottwittrock** [comment]
I'd like to do this exact same use case. Has anyone found a work around? 

> @m3hari the admin package does more than that. For example, I'd like to decode a firebase id token and get custom claims from it.

**Comment by m3hari** [comment]
just verifying token was my use case

**Comment by step135** [comment]
What about REST API? My issue here was closed today claiming that I can use AUTH REST API to manage users. Do you agree with lahirumaramba (Firebase employee)?

**Comment by 0x80** [comment]
@step135 I don't think that is true. Decoding a token I wouldn't categorize as "managing users" and looking at the list on the right side of the API reference I don't see it either: https://firebase.google.com/docs/reference/rest/auth

**Comment by jdgamble555** [comment]
The solution to this problem is "Firebase Admin Lite" which would basically have a REST API under the hood. For those who don't know, Firestore has a "lite" version, but you can't use auth or anything meaningful with it for the moment. It does, however, help with non-logged queries.

- https://github.com/firebase/firebase-admin-node/issues/1879

Also, you may want to vote on the request and maybe it will get more attention:

- https://firebase.uservoice.com/forums/948424-general/suggestions/48355772-firebase-admin-lite

J

**Comment by JedPattersonn** [comment]
If you want to decode the auth token, I've just created a package that does this, just pass in your token and project ID and it will decode it.

Works on the edge https://www.npmjs.com/package/firebase-edge-auth

**Comment by spacerrsdreams** [comment]
That would be great, currently I am getting issue with firebase admin on Deno.

```
Deno.env.set("GOOGLE_SDK_NODE_LOGGING", "false");

import {
  Application,
  Router,
  Context,
} from "https://deno.land/x/oak@v17.1.4/mod.ts";
import {
  initializeApp,
  cert,
  getApps,
} from "https://esm.sh/firebase-admin@13.1.0/app";
import { getAuth } from "https://esm.sh/firebase-admin@13.1.0/auth";

// Load Firebase Admin credentials
const firebaseConfig = JSON.parse(
  Deno.readTextFileSync("./serviceAccountKey.json")
);

console.log(firebaseConfig);

if (!getApps().length) {
  initializeApp({
    credential: cert(firebaseConfig),
  });
}

const authMiddleware = async (ctx: Context, next: () => Promise<unknown>) => {
  try {
    const authHeader = ctx.request.headers.get("Authorization");

    if (!authHeader?.startsWith("Bearer ")) {
      ctx.response.status = 401;
      ctx.response.body = { error: "Unauthorized: No token provided" };
      return;
    }

    const idToken = authHeader.split("Bearer ")[1];
    const decodedToken = await getAuth().verifyIdToken(idToken);

    console.log("Authenticated User:", decodedToken.uid);
    ctx.state.user = decodedToken; // Store user info in context for later use

    await next();
  } catch (error) {
    console.error("Authentication Error:", error);
    ctx.response.status = 401;
    ctx.response.body = { error: "Unauthorized: Invalid token" };
  }
};

const router = new Router();
router.get("/protected", authMiddleware, (ctx) => {
  ctx.response.body = {
    message: "You are authenticated!",
    user: ctx.state.user,
  };
});

const app = new Application();
app.use(router.routes());
app.use(router.allowedMethods());

console.log("Server running on http://localhost:8000");
await app.listen({ port: 8000 });
```

Error:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'GOOGLE_SDK_NODE_LOGGING')
    at Object.S [as log] (https://esm.sh/google-logging-utils@0.0.2/denonext/google-logging-utils.mjs:4:5484)
    at https://esm.sh/gcp-metadata@6.1.1/denonext/gcp-metadata.mjs:4:2813
    at https://esm.sh/gcp-metadata@6.1.1/denonext/gcp-metadata.mjs:4:452
    at https://esm.sh/gcp-metadata@6.1.1/denonext/gcp-metadata.mjs:4:6442
```
