### ISSUE TITLE
With preferRest: true option set, I am unable to connect to auth emulator

### ISSUE THREAD

**Issue by sushantdhiman** [firebase/firebase-admin-node#2016]
### Describe your environment

  * Operating System version: Arch Linux
  * Firebase SDK version: 11.4.0
  * Firebase Product:  auth, firestore, storage
  * Node.js version: 18.x
  * NPM version: 8.19.1

**Additional related dependencies** 
```
@google-cloud/logging@10.3.2
@google-cloud/pubsub@3.2.1
firebase-admin@11.4.0
```

### Describe the problem

With `preferRest: true` option set, I am unable to connect to auth emulator

#### Steps to reproduce:

Here is my firebase initialization code

```diff
import { initializeApp, applicationDefault } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { initializeFirestore } from 'firebase-admin/firestore';

export const app = initializeApp({                                                                                                
  credential: applicationDefault(),
  projectId: process.env.GCLOUD_PROJECT,
});

export const auth = getAuth(app);
---export const firestore = initializeFirestore(app);
+++export const firestore = initializeFirestore(app, { preferRest: true });
```

When I run my application with `preferRest: true`, I get this error. It seems like emulators are not detected with this option.

```
Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
  at GoogleAuth.getApplicationDefaultAsync (/home/node/app/node_modules/google-auth-library/build/src/auth/googleauth.js:209:19)
  at GoogleAuth.getClient (/home/node/app/node_modules/google-auth-library/build/src/auth/googleauth.js:635:17)
  at GrpcClient.createStub (/home/node/app/node_modules/google-gax/src/fallback.ts:280:27)
Caused by: Error: 
  at L0.getAll (/home/node/app/lib/server.js:113:509361)
  at ta.get (/home/node/app/lib/server.js:113:32416)
  at Function.findByIdentifier (/home/node/app/src/database/user.ts:115:44)\n
```

Application works correctly without `preferRest` option.

**Comment by lahirumaramba** [comment]
Hi @sushantdhiman, `preferRest` option is in firestore or it is a bit strange that you are experiencing issues with the auth API. You might have already done this, but just to confirm did you set the environment variables for Firestore and Auth emulator?

```
export FIREBASE_AUTH_EMULATOR_HOST="localhost:9099"
export FIRESTORE_EMULATOR_HOST="localhost:8080"
```

**Comment by lahirumaramba** [comment]
I am also unable to reproduce this.

**Comment by Gbuomprisco** [comment]
I am experiencing the same. 

From what I can tell, the function `refreshTokenNoCache` is using the constant below:

```
 const url = OAuth2Client.GOOGLE_OAUTH2_TOKEN_URL_
 ```

**Comment by sushantdhiman** [comment]
> did you set the environment variables for Firestore and Auth emulator?

I can confirm those environment variables are set.

Applications works correctly without `preferRest: true`, I am also facing this exact issue in another project.

**Comment by ganey** [comment]
I have this issue too. When you enable `preferRest`, it seems like the auth emulator tries to setup credentials for the google-gax fallback?

It has the correct address set in the env passed into `createStub` and `customServicePath` is true, but this.auth.getClient() errors out.

https://github.com/googleapis/gax-nodejs/blob/main/src/fallback.ts#L280

**Comment by lahirumaramba** [comment]
Hey everyone, thank you for your patience on this. We have identified the root cause and the team is currently working on a fix.

**Comment by sushantdhiman** [comment]
@lahirumaramba Can you suggest some workaround while https://github.com/googleapis/gax-nodejs/issues/1409 is open? Perhaps we can mock/stub some methods so it works for tests?

**Comment by maccman** [comment]
Also running into this.

**Comment by MarkDuckworth** [comment]
We have some momentum on a fix, but in the meantime there are two possible workarounds.

First, you could disable preferRest when using the emulator. 
```
    const db = initializeFirestore(app, {
        preferRest: !process.env.FIRESTORE_EMULATOR_HOST
    });
```

Second, you can create this auth object for use with the emulator.

```
import { initializeApp, applicationDefault } from 'firebase-admin/app';
import { initializeFirestore } from 'firebase-admin/firestore';

export const app = initializeApp({
    credential: applicationDefault(),
    projectId: process.env.GCLOUD_PROJECT,
});

// Workaround pt 1 - add this createEmulatorAuth function
function createEmulatorAuth() {
    return {
        async getClient() {
            return {
                async getRequestHeaders() {
                    return {Authorization: 'Bearer owner'};
                }
            };
        },
    };
}

async function main() {
    const db = initializeFirestore(app, {
        preferRest: true
    });

    // Workaround pt 2 - Pass emulator auth here
    if (process.env.FIRESTORE_EMULATOR_HOST) {
        db.settings({
            auth: createEmulatorAuth()
        });
    }

    await db.collection("foo").add({time: Date.now()})
    const result = await db.collection("foo").get();

    console.log(result.size);
}
main();
```

**Comment by johnnyoshika** [comment]
I don't seem to have any trouble connecting to auth emulator with `preferRest`.  My config:


`config/firebase.ts`

```
import { initializeApp } from 'firebase-admin/app';
import { getAuth } from 'firebase-admin/auth';
import { getFirestore } from 'firebase-admin/firestore';
import { getStorage } from 'firebase-admin/storage';

const app = initializeApp();

const auth = getAuth(app);

const db = getFirestore(app);

db.settings({
  ignoreUndefinedProperties: true,
  preferRest: true,
});

const storage = getStorage(app);

export { auth, db, storage };
```

**Comment by johnnyoshika** [comment]
I stand to be corrected. Although my app runs fine with auth emulator when `preferRest` is true, unit tests now time out and fail. This fixed it for me:

```
db.settings({
  ignoreUndefinedProperties: true,
  preferRest: !process.env.JEST_WORKER_ID,
});
```

**Comment by sushantdhiman** [comment]
**Update for `firebase-admin@14.4.0`**

This issue still exists but since we are using custom `settings`,  a new issue may appear

```js
TypeError: auth.fetch is not a function
    at serviceStub.<computed> [as batchGetDocuments] (/home/node/app/node_modules/google-gax/build/src/fallbackServiceStub.js:135:18)
    at /home/node/app/node_modules/@google-cloud/firestore-api/build/src/v1/firestore_client.js:257:29
    at /home/node/app/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:39:28
    at /home/node/app/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at StreamProxy.setStream (/home/node/app/node_modules/google-gax/build/src/streamingCalls/streaming.js:218:32)
    at StreamingApiCaller.call (/home/node/app/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:55:16)
    at /home/node/app/node_modules/google-gax/build/src/createApiCall.js:110:37
```

To fix that we have to manually pass `fetch` instance to `auth` settings.

```diff
  if (process.env.FIRESTORE_EMULATOR_HOST) {
    firestoreInstance.db.settings({
      auth: {
+      fetch: global.fetch,
        async getClient() {
          return {
            async getRequestHeaders() {
              return { Authorization: 'Bearer owner' };
            },
          };
        },
      },
    });
  }

```
