### ISSUE TITLE
[messaging] TypeError: Value is not an object: undefined

### ISSUE THREAD

**Issue by Tom3652** [firebase/firebase-admin-node#2037]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MongoDB Atlas Trigger (Realm App)
  * Firebase SDK version: 11.4.1
  * Firebase Product: messaging 
  * JS SDK Version: [3.18.0](https://github.com/mongodb/stitch-js-sdk/releases/tag/v3.18.0)
  * NPM version: I don't know

### [REQUIRED] Step 3: Describe the problem

Executing `admin.messaging().sendMulticast(message)` returns an error and is not working anymore after upgrading to `firebase-admin: 11.4.1` from `11.0.1` and with the release of [fastify/busboy 1.2.0](https://github.com/firebase/firebase-admin-node/issues/1902#issuecomment-1373978366) : 

```
uncaught promise rejection: TypeError: Value is not an object: undefined
```

The difference with my previous issue #1902 is that now `messaging().sendMulticat(message)` is crashing and no longer deliver the push notification.

#### Steps to reproduce:

1. Create a MongoDB Atlas trigger
2. Add `firebase-admin` as external dependency and make sure it's `11.4.1` 
3. Add the service-account.json as a `value`
4. Run the code with the below code  

#### Relevant Code:

```
exports = async function() {

  const admin = require("firebase-admin");
  const json_creds = context.values.get("service_account_value_name");
  	  
    const title = "Test";
    const body = "This is a test";
   
    const message= {
      android: {
        notification: {
          title: title,
          sound: "default",
          body: body,
        },
      },
      apns: {
        payload: {
          aps: {
            alert: {
              title: title,
              body: body,
            },
            mutableContent: 1,
            contentAvailable: 1
          }
        },
      },
      tokens: ["device_token_1", "device_token_2"]
    };
    	
    admin.initializeApp({
        credential: admin.credential.cert(JSON.parse(json_creds))
      });
  
    admin.messaging().sendMulticast(message);

    console.log("Messages sent !");
  }
}
```

**Comment by Tom3652** [comment]
I have rolled back to `11.0.1` to see the difference and i am getting the following error : 

```
TypeError: Arguments must be Buffers
	at compare (<eval>:344:13(19))
	at node_modules/@fastify/busboy/deps/streamsearch/sbmh.js:181:65(304)
	at node_modules/@fastify/busboy/deps/streamsearch/sbmh.js:82:24(41)
	at node_modules/@fastify/busboy/deps/dicer/lib/Dicer.js:107:23(92)
	at T (<eval>:10:22717(45))
	at <eval>:10:25821(108)
	at <eval>:10:25847(113)
	at d (<eval>:10:14414(11))
	at <eval>:10:4454(115)
	at <eval>:10:13336(285)
	at C (<eval>:10:11803(20))
	at A (<eval>:10:11681(31))
```

But the push notification is sent successfully, in `11.4.1` it's not sent at all.

**Comment by stelldogg** [comment]
I'm seeing the same issue, where updating from 11.4.0 to 11.4.1 is causing this crash.  It appears that [this](https://github.com/firebase/firebase-admin-node/commit/d23b1c52a801436476b6ed95699d49d1fcdb8f1e) change has pushed 'undefined' as a value into a the JWT verify flow, which might match the error.  I will try to get my function dependencies to refresh, as it might be a stale package (jsonwebtoken) causing the failure.

**Comment by stelldogg** [comment]
No change in behavior after adding `jsonwebtoken` 9.0.0 as a dependency directly.

**Comment by davidkessler-ch** [comment]
Same issue here...

**Comment by Tom3652** [comment]
Sorry i don't know node JS that much, i only use a MongoDB Atlas Trigger to see this behavior... :(

**Comment by lahirumaramba** [comment]
No worries, are you able to share a complete error log so we can track down where it is throwing the error?

**Comment by stelldogg** [comment]
@lahirumaramba the errors posted above are all that are given when the error is generated by the MongoDB function, apologies.  

If it helps, here are a couple extra details:

payload:
`{"notification":{"body":"Your video is ready!","title":"New Video"},"tokens":[<my-device-token>]}`

call:
```
const admin = require('firebase-admin');
admin.messaging().sendMulticast(message)
```

**Comment by Tom3652** [comment]
> No worries, are you able to share a complete error log so we can track down where it is throwing the error?

Sorry for the late answer, there is no more logs than this from the Atlas trigger... 
However, i think it can be related to any changes made between the working version and this one that is not working at all.

**Comment by Gregliest** [comment]
Has there been any progress on this? I'm still running into this issue on version 11.7.0

**Comment by d66ni** [comment]
I have the same issue, are there any news about this topic? Actually using version 11.9.0.

**Comment by jeanmartin** [comment]
11.10.1, also using MongoDB Atlas functions, same error :/

**Comment by Jzuni97** [comment]
Did anyone every resolve this? Using version 11.11.0 in MongoDB Atlas functions and still getting same error...

**Comment by bnuby** [comment]
I downgraded to v10.0.0 and it works well.

**Comment by davidkessler-ch** [comment]
I can't believe that this has still not been fixed😟. (now using 12.0.0)

**Comment by richparker** [comment]
Still no update on this? 

I get the same error when using 12.0.0. Had to downgrade to 10.0.0 for it to work.

**Comment by MadalinSava** [comment]
Same issue here, 10.0.0 is working but 12 is not.

**Comment by Luca-21** [comment]
im using the last version 12.1.1 and i have the same issue, how can i downgrade the version of sdk to fix this?

**Comment by madhanhere** [comment]
I faced the error with version all 10.0.0 and 11v and 12v

I solved by using the following approach.

I used axios and google-auth-library

```
import axios from "axios";
  const { JWT } = require("google-auth-library");
const json_creds = JSON.parse(context.values.get("service_account_value_name"));

 const getAccessToken = async () => {
    try {
      const client = new JWT({
        email: json_creds.client_email,
        key: json_creds.private_key,
        scopes: ["https://www.googleapis.com/auth/firebase.messaging"],
      });
      const accessToken = await client.authorize();
      return accessToken.access_token;
    } catch (err) {
     throw new Error(err.message)
    }
  };

const accessToken = await getAccessToken()

const notification = {
  message: {
    notification: {
    title: "hello",
    body: "this is a new remainder",
    },
  token: "your_device_token"
  },
};

await axios.post(`https://fcm.googleapis.com/v1/projects/your_projectid/messages:send`, message, {
  headers: {
    Authorization: `Bearer ${accessToken}`,
    "Content-Type": "application/json",
  },
});
```


*note:- you cannot send multicast or sendAll.

**Comment by Tom3652** [comment]
I have ended up calling a Python Cloud function that is working fine instead of using the Node SDK, but that adds an extra HTTPS call.
