### ISSUE TITLE
CreateCustomToken() in Cloud Functions

### ISSUE THREAD

**Issue by mikeal** [firebase/firebase-admin-node#205]
I'm not actually sure if this is a feature request or something that I can do given some kind of special configuration of the admin in Cloud Functions.

By default, when I try to use the admin in Cloud Functions to CreateCustomToken() I get:

```
Error: createCustomToken() requires a certificate with "private_key" set.
    at FirebaseAuthError.Error (native)
    at FirebaseAuthError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:85:28)
    at new FirebaseAuthError (/user_code/node_modules/firebase-admin/lib/utils/error.js:143:16)
    at FirebaseTokenGenerator.createCustomToken (/user_code/node_modules/firebase-admin/lib/auth/token-generator.js:76:19)
    at Auth.createCustomToken (/user_code/node_modules/firebase-admin/lib/auth/auth.js:102:37)
    at exports.createToken.functions.firestore.document.onCreate.event (/user_code/index.js:52:25)
    at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:59:27)
    at next (native)
    at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:28:71
```

If there is a way to make this work today I'd love to do it. If not, consider this a feature request :)

**Comment by hiranya911** [comment]
You can make it work by shipping a service account credential with your function and using it when calling `admin.initializeApp()`. There's a long standing feature request to support this feature without explicit service accounts.

**Comment by hiranya911** [comment]
Official sample: https://github.com/firebase/functions-samples/blob/master/username-password-auth/functions/index.js#L91
