### ISSUE TITLE
Various issues when used with Cloudflare Pages

### ISSUE THREAD

**Issue by JorritSalverda** [firebase/firebase-admin-node#2069]
### [READ] Step 1: Are you in the right place?

When running the following Typescript code in Cloudflare Pages on the server-side - in a Remix `server.ts` file:

```
import { applicationDefault, initializeApp as initializeAdminApp } from "firebase-admin/app";

initializeAdminApp({
  credential: applicationDefault(),
})
```

 I get the following error:

```
[pages:err] TypeError: globalThis.XMLHttpRequest is not a constructor
    at checkTypeSupport (/private/Users/jorrit/work/simpl/simpl-energy-website/functions/[[path]].js:15751:17)
    at node_modules/rollup-plugin-node-polyfills/polyfills/http-lib/capability.js (/private/Users/jorrit/work/simpl/simpl-energy-website/functions/[[path]].js:15764:177)
    at /private/Users/jorrit/work/simpl/simpl-energy-website/functions/[[path]].js:7:52
    at node_modules/rollup-plugin-node-polyfills/polyfills/http-lib/request.js (/private/Users/jorrit/work/simpl/simpl-energy-website/functions/[[path]].js:17874:5)
    at /private/Users/jorrit/work/simpl/simpl-energy-website/functions/[[path]].js:7:52
    at node-modules-polyfills:http (/private/Users/jorrit/work/simpl/simpl-energy-website/functions/[[path]].js:18033:5)
    at /private/Users/jorrit/work/simpl/simpl-energy-website/functions/[[path]].js:7:52
    at node-modules-polyfills-commonjs:http (/private/Users/jorrit/work/simpl/simpl-energy-website/functions/[[path]].js:18133:21)
    at /private/Users/jorrit/work/simpl/simpl-energy-website/functions/[[path]].js:10:47
    at node_modules/firebase-admin/lib/utils/api-request.js (/private/Users/jorrit/work/simpl/simpl-energy-website/functions/[[path]].js:22423:76)
```

This is caused by Cloudflare Workers only supporting _fetch_ not _XMLHttpRequest_.

Another issue I run into when using

```
import * as admin from "firebase-admin";
import { applicationDefault, initializeApp as initializeAdminApp } from "firebase-admin/app";

initializeAdminApp({
  credential: applicationDefault(),
})

const adminAuth = admin.auth();
```

Is that I get the following error:

```
✘ [ERROR] Could not resolve "@firebase/database-compat/standalone"

    node_modules/firebase-admin/lib/app/firebase-namespace.js:106:41:
      106 │ ...ject.assign(fn, require('@firebase/database-compat/standalone'));
          ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./standalone" is not currently exported by package "@firebase/database-compat":

    node_modules/@firebase/database-compat/package.json:16:13:
      16 │   "exports": {
         ╵              ^

  None of the conditions provided ("types", "node") match any of the currently active conditions ("default", "require", "worker"):

    node_modules/@firebase/database-compat/package.json:31:20:
      31 │     "./standalone": {
         ╵                     ^

  Consider enabling the "types" condition if this package expects it to be enabled. You can use "conditions: ['types']" to do that:

    node_modules/@firebase/database-compat/package.json:32:6:
      32 │       "types": "./dist/database-compat/src/index.standalone.d.ts",
         ╵       ~~~~~~~

  You can mark the path "@firebase/database-compat/standalone" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
```

Any chance this npm package can be made compatible with Cloudflare Pages/Workers?

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Cloudflare Pages
  * Firebase SDK version: 11.5.0
  * Firebase Product: auth
  * Node.js version: v19.6.0 (on my workstation, but not in Cloudflare Pages as it doesn't spin up a node environment)
  * NPM version: 9.4.0

#### Steps to reproduce:

```bash
npx create-remix@latest

? Where would you like to create your app? ./my-remix-app
? What type of app do you want to create? Just the basics
? Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets. Cloudflare Pages
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes

cd my-remix-app
npm install firebase
npm install firebase-admin
touch ./app/firebase.server.ts
```

Add the following content to `app/firebase.server.ts`:

```
import * as admin from "firebase-admin";
import { applicationDefault, initializeApp as initializeAdminApp } from "firebase-admin/app";
import { signInWithEmailAndPassword, getAuth } from "firebase/auth";

// errors with 'TypeError: globalThis.XMLHttpRequest is not a constructor'
initializeAdminApp({
  credential: applicationDefault(),
})

// errors with 'Could not resolve "@firebase/database-compat/standalone"'
const adminAuth = admin.auth();

async function signIn(email: string, password: string) {
  const auth = getAuth();
  return signInWithEmailAndPassword(auth, email, password);
}

export { signIn }
```

And update the `app/routes/index.tsx` file to

```
import type { ActionArgs } from "@remix-run/cloudflare";
import { Form } from "@remix-run/react";
import { signIn } from "~/firebase.server";

export const action = async ({ request }: ActionArgs) => {
  let formData = await request.formData();

  let email = formData.get("email");
  let password = formData.get("password");

  const { user } = await signIn(email as string, password as string);
}

export default function Index() {
  return (
    <Form method="post">
      <label>
        Email
        <input type="email" name="email" />
      </label>
      <label>
        Password
        <input type="password" name="password" />
      </label>
      <button type="submit">
        Sign In
      </button>
    </Form>
  );
}
```

Now run `npm run dev` and see it fail.

**Comment by lahirumaramba** [comment]
Hi @JorritSalverda ,

`firebase-admin` requires a full Node.js runtime and is not supported on Cloudflare workers. The SDK is currently incompatible with bundling tools like `webpack`.

**Comment by JorritSalverda** [comment]
Hi @lahirumaramba

That's a pity. I think it has mostly to do with the database access. If I store session state in Cloudflare's KV store instead and check the JWT with a library that does run in Cloudflare Workers I don't need `firebase-admin` and am just fine. It does block me from using Firestore though.

**Comment by koistya** [comment]
As a workaround, it is possible to interact with Firestore (and other Google APIs) from under Cloudflare Workers or Cloudflare Pages using [Firestore REST API](https://firebase.google.com/docs/firestore/use-rest-api), for example:

```ts
import { Hono } from "honor"; // routing library for Cloudfalre Workers
import { getAccessToken } from "web-auth-library/google"; // auth library for Cloudflare Workers

const app = new Hono();

app.get("/example", ({ env }) => {
  const accessToken = await getAccessToken({ credentials: env.GOOGLE_CLOUD_CREDENTIALS });
  const prefixURL = `https://firestore.googleapis.com/v1/projects/${env.GOOGLE_CLOUD_PROJECT}/databases/(default)/documents/`;
  const res = await fetch(`${prefixURL}/cities/LA`, {
    headers: { "Authorization": `Bearer ${accessToken}` }
  });
  ...
});
```

https://github.com/kriasoft/web-auth-library

**Comment by lahirumaramba** [comment]
Hey folks, I am gathering details on similar use cases (this is not a promise for a feature, btw :)). Right now, unfortunately the SDK does not work on edge runtimes, and as @koistya mentioned using the REST API would be your best bet for now. If you have some time, could you folks share a few more details about your use-cases, please? This will help us better understand your requirements and consider supporting edge and other similar runtimes in the future.

**Comment by chrisspiegl** [comment]
I just found this question while researching to use Cloudflare workers for SSR in one of my projects. A connection to firestore would be crucial for us in this regard.

Our tech stack is based on NUXT.js 3 and VueFire.

Having edge functions render SSR content would help with performance a lot. And not having to individually wrap the REST api would make things incredibly easy. 

Cheers.

**Comment by chrisspiegl** [comment]
Adding to this, it seems like Cloudflare is working on Node.js compatibility for things like this. ([Source Blog Post](https://blog.cloudflare.com/workers-node-js-asynclocalstorage/))

But, I have been trying to get Cloudflare and Firebase / Firestore SSR to work with polyfills like [Unenv](https://github.com/unjs/unenv) and all that (this was before the new blog post from Cloudflare).

Feels like I came pretty far but then Firebase decides to use another freaking `node.js` library and it all breaks again.

**Comment by lahirumaramba** [comment]
Thanks for sharing this @chrisspiegl !
I have been running some experiments on validating Firebase tokens on edge runtimes here [lahirumaramba/edge_token_verifier](https://github.com/lahirumaramba/edge_token_verifier), but it sounds like the ask is for more than just validating JWTs (access to RTDB/Firestore services etc.).

**Comment by mgarf** [comment]
also want to +1 on getting Firebase Auth for edge runtimes.

**Comment by emalamisura-c2m** [comment]
+1 for this, really annoying and quickly becoming the norm with SSR on edge.

**Comment by maccman** [comment]
+1

**Comment by brian-gee** [comment]
+1, can't believe such a standard feature isn't supported.

**Comment by step135** [comment]
It could be done directly and easy through REST API calls with admin privileges. Managing user accounts would be the base. But nothing is described in documentation and it looks like Firebase is already dying as they don't work on including this and many other trivial functionalities that other databases already have.

**Comment by gustavopch** [comment]
I’ve been saying the same thing. Compare Firebase releases with Supabase. Firebase looks mostly stopped in time. I’ve already lost much of my hope in its future.

**Comment by step135** [comment]
And for them it is a question of a short moment to describe REST API for admins to at least manage user accounts. But they don't do it. Does anyone know why?

**Comment by ajzbc** [comment]
+1

**Comment by clibequilibrium** [comment]
> And for them it is a question of a short moment to describe REST API for admins to at least manage user accounts. But they don't do it. Does anyone know why?

Do you mean this? https://firebase.google.com/docs/reference/rest/auth

**Comment by treeder** [comment]
Would anyone be interested in a lightweight library using only the REST APIs for these Google services? We've written our own little JS modules to access these services from Cloudflare and Bun apps (neither of which work with Google's libraries).

**Comment by clibequilibrium** [comment]
Found this specifically for admin sdk support on Cloudflare network https://github.com/Marplex/flarebase-auth

**Comment by step135** [comment]
> Found this specifically for admin sdk support on Cloudflare network https://github.com/Marplex/flarebase-auth

Useless for me as it has scope of user and not admin.

**Comment by step135** [comment]
> Found this specifically for admin sdk support on Cloudflare network https://github.com/Marplex/flarebase-auth

Useless as it can not manage accounts (list and delete).

**Comment by clibequilibrium** [comment]
> > Found this specifically for admin sdk support on Cloudflare network https://github.com/Marplex/flarebase-auth
> 
> 
> 
> Useless as it can not manage accounts (list and delete).
> 
> 

Fork it and add delete.

**Comment by clibequilibrium** [comment]
Another solution could be enabling `nodejs_compat` https://developers.cloudflare.com/workers/runtime-apis/nodejs/  to enable compatibility with nodejs. But you would need to fork admin sdk and do as per documentation: 

```ts
// Do this:
import { Buffer } from 'node:buffer';

// Do not do this:
import { Buffer } from 'buffer';
```

**Comment by prvashisht** [comment]
+1, Firestore via admin SDK is breaking in Cloudflare pages in my Nuxt3 application's server routes.

**Comment by gustavopch** [comment]
Some functions I wrote with help of GPT-4 to use Firestore via its REST API: https://gist.github.com/gustavopch/ca4d15faa5ab2e76ba918b7adeba7fa2

My advise: don't count on Firebase shipping anything.

**Comment by Joelsz** [comment]
firebase-admin `initializeApp([credential: cert(JSON.parse(c.env.SERVICE_ACCOUNT_JSON))])` breaks on Cloudflare Pages with the following error:

```
Credential implementation provided to initializeApp() via the "credential" property
    failed to fetch a valid Google OAuth2 access token with the following error:
    "[unenv] crypto.createSign is not implemented yet!".
```
Is there any workaround to init the app without using the incompatible crypto functions?

**Comment by treeder** [comment]
The only workaround is to not use the firebase-admin library, use https://github.com/kriasoft/web-auth-library for authentication then call the REST API.

**Comment by Joelsz** [comment]
Thanks @treeder.

Can I somehow copy the crypto function(s) from `web-auth-library` into my local `firebase-admin` to make it work? I'd really keep my current implementation after spending quite a bit of time on it locally.

**Comment by treeder** [comment]
Good question, worth a try!  I'm sure a lot of people would like to see that.

**Comment by Moi6AP** [comment]
Please professionals who can recreate Firebase-admin with Rest API and use KV to cache session. 😭🙏🏻
I already implemented the way to cache session, also got the token to use Rest API and some Firestore functions. Who wants to sign up to make this happen? 😭🙏🏻

**Comment by Moi6AP** [comment]
https://github.com/samuelgozi/firebase-firestore-lite/
https://github.com/samuelgozi/firebase-auth-lite/
https://github.com/samuelgozi/firebase-storage-lite

Apparently they all work with cloudflare workers

**Comment by Joelsz** [comment]
Can anyone advise if the support for `crypto.createSign()` being added [here](https://github.com/cloudflare/workerd/issues/3172#issuecomment-2688752469) (with limitation) will suffice firebase-admin usage on Cloudflare Workers environment?

**Comment by davext** [comment]
Gonna try it again to see if this fixes it https://developers.cloudflare.com/changelog/2025-04-08-nodejs-crypto-and-tls/

**Comment by clibequilibrium** [comment]
> Gonna try it again to see if this fixes it https://developers.cloudflare.com/changelog/2025-04-08-nodejs-crypto-and-tls/

I doubt it as there is still dependency on 'fs' in admin package.

**Comment by gustavopch** [comment]
@clibequilibrium You mean https://github.com/firebase/firebase-admin-node/blob/a46086b61f58f07426a6ca103e00385ae216691d/src/app/lifecycle.ts and https://github.com/firebase/firebase-admin-node/blob/a46086b61f58f07426a6ca103e00385ae216691d/src/app/credential-internal.ts? If only these files, one could probably patch them without much effort.

**Comment by clibequilibrium** [comment]
> [@clibequilibrium](https://github.com/clibequilibrium) You mean https://github.com/firebase/firebase-admin-node/blob/a46086b61f58f07426a6ca103e00385ae216691d/src/app/lifecycle.ts and https://github.com/firebase/firebase-admin-node/blob/a46086b61f58f07426a6ca103e00385ae216691d/src/app/credential-internal.ts? If only these files, one could probably patch them without much effort.

lmk how it goes!

**Comment by prmichaelsen** [comment]
Wow, that is downright unfortunate. Would really love to see a fix for this soon. I was in the middle of porting all my applications from Vercel because their CEO did a photo op with a mass murderer and now I've hit a wall.

**Comment by Futhark** [comment]
@prmichaelsen have you checked this on latest wrangler with nodejs compatibility with current date? These `http` APIs were implemented by Cloudflare two or more months ago. So it is possible that with valid compatibility flags it will just work,

**Comment by prmichaelsen** [comment]
I tried my luck with <nodejscompat> but it didn't seem to work as expected.

```sh
wrangler deploy .output/server/index.mjs \
  --assets .output/public \
  --name arthouse1312 \
  --compatibility-date 2025-10-24 \
  --compatibility-flags nodejs_compat \ 
  --route "arthouse1312.com/*"
```

```ts
// vite.config.ts
import { defineConfig } from 'vite'
import { tanstackStart } from '@tanstack/react-start/plugin/vite'
import viteReact from '@vitejs/plugin-react'
import viteTsConfigPaths from 'vite-tsconfig-paths'
import tailwindcss from '@tailwindcss/vite'
import { nitroV2Plugin } from '@tanstack/nitro-v2-vite-plugin'

const config = defineConfig({
  build: {
    sourcemap: true, // Enable source maps for production
    rollupOptions: {
      output: {
        sourcemapIgnoreList: () => false, // Include all files in source maps
      },
    },
  },
  server: {
    sourcemapIgnoreList: () => false, // Don't ignore any files in dev server source maps
  },
  plugins: [
    nitroV2Plugin({
      preset: 'cloudflare-module',
      compatibilityDate: '2025-10-24',
      cloudflare: {
        wrangler: {
          compatibility_flags: ['nodejs_compat'],
        },
      },
    }),
    // this is the plugin that enables path aliases
    viteTsConfigPaths({
      projects: ['./tsconfig.json'],
    }),
    tailwindcss(),
    tanstackStart(),
    viteReact(),
  ],
})

export default config
```

**Comment by danyelkoca** [comment]
Any update on this one?

_firebase-admin requires a full Node.js runtime and is not supported on Cloudflare workers. The SDK is currently incompatible with bundling tools like webpack._

**Comment by anhcraft** [comment]
I recently ran into this issue as well... At minimum, it’s possible to implement your own JWT verification when using only Firebase Auth. However, I'd really appreciate official support from the Firebase team for Cloudflare worker and other edge runtimes.
