### ISSUE TITLE
Package @firebase/database-compat is private or doesn't exist

### ISSUE THREAD

**Issue by NtTestAlert** [firebase/firebase-admin-node#2181]
### Describe your environment

  * Firebase SDK version: "firebase-admin": "^11.0.0" (11.0.0, but problem exists on higher versions too)

### Describe the problem

Cannot install package:
```npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@firebase/database-compat/-/database-compat-0.2.1.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@firebase/database-compat@https://registry.npmjs.org/@firebase/database-compat/-/database-compat-0.2.1.tgz' is not in this registry.
```

https://www.npmjs.com/package/@firebase/database-compat
Asks for log-in

**Comment by dready** [comment]
Same Problem, trying to install the firebase-admin package throws an error although we have not changed anything for weeks.

Updating to current version did not fix the problem. currently firebase-admin is NOT WORKING at all because of this.
```
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find package "@firebase/database-compat@0.3.4" required by "firebase@9.22.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Couldn't find package "@grpc/proto-loader@^0.6.13" required by "@firebase/firestore@3.12.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@grpc/proto-loader@^0.7.0" required by "@grpc/grpc-js@~1.7.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Couldn't find package "@firebase/remote-config-types@0.3.0" required by "@firebase/remote-config-compat@0.2.4" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/local/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:36590:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/local/lib/node_modules/yarn/lib/cli.js:323:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by aladdin-wattar** [comment]
Same issue here the npm package is 404 not found. it's breaking deployments

**Comment by dready** [comment]
It might be a npm internal problem.. currently they have authentication problems.. https://status.npmjs.org/

**Comment by aladdin-wattar** [comment]
looks like they are deprecating the package and something went wrong, updating the version manually on package.json solved the problem upgrade to 11.8.0

**Comment by NtTestAlert** [comment]
> looks like they are deprecating the package and something went wrong, updating the version manually on package.json solved the problem upgrade to 11.8.0

I tried installing the newest version, and it still uses that package, but this time it throws Service Unavailable so it might be a problem with NPM

Still, this is probably not the best way to deprecate a package, even if it went "right"

**Comment by dready** [comment]
yepp, npm is having major outage.

**Comment by NtTestAlert** [comment]
Bug was caused by npm outage, seems fixed
