### ISSUE TITLE
Deploy issues, syntax errors in firebase-admin?

### ISSUE THREAD

**Issue by enricribas** [firebase/firebase-admin-node#228]
### [READ] Step 1: Are you in the right place?

I think so.

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: _?_the web?___
  * Firebase SDK version: _____
  * Library version: _5.8.2____
  * Firebase Product: n/a_____ (auth, database, storage, etc)

#### Steps to reproduce:

firebase deploy --only functions -P production 

Try to deploy cloud functions, getting syntax errors not in my code but in firebase-admin.
I've tried npm install. Removing node_modules, reinstalling, etc.

```
⚠  functions[v1]: Deployment error.
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: /user_code/node_modules/firebase-admin/node_modules/sntp/lib/index.js:19
exports.time = async function (options = {}) {
                     ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/hawk/lib/index.js:5:16)
```

I don't use hawk, or sntp in my code. Seems that error is coming from firebase-admin interns?
Have not upgraded or changed this from last deploy that did work.

Here's my entire package.json dependencies 
```
  "dependencies": {
    "@sendgrid/mail": "^6.1.4",
    "express": "^4.16.2",
    "firebase-admin": "^5.8.2",
    "firebase-functions": "^0.8.1",
    "handlebars": "^4.0.10",
    "html-email-to-text": "^1.0.4",
    "lodash": "^4.17.5",
    "sendgrid": "^5.2.3",
    "uuid": "^3.1.0"
  },
```

**Comment by evenmatrix** [comment]
Same issue here after function is deployed and tried to be executed :

"firebase-admin": "^5.8.2",

/user_code/node_modules/firebase-admin/node_modules/sntp/lib/index.js:19
exports.time = async function (options = {}) {
                     ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/hawk/lib/index.js:5:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/request/request.js:9:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by hiranya911** [comment]
What version of NPM are you using? Can you also try `npm ls sntp` and share the output? Here's what I get (for the given `package.json`):

```
└─┬ @sendgrid/mail@6.2.1
  └─┬ @sendgrid/client@6.2.1
    └─┬ request@2.85.0
      └─┬ hawk@6.0.2
        └── sntp@2.1.0 
```

According to this sntp and hawk are dependencies for `sendgrid` and not `firebase-admin`. However, in this case NPM installed the latest version (5.10.0) of `firebase-admin` in my project. This is because your `package.json` specifies the dependency as `^5.8.2.`. If I use `5.8.2` strictly, this is what I get:

```
├─┬ @sendgrid/mail@6.2.1
│ └─┬ @sendgrid/client@6.2.1
│   └─┬ request@2.85.0
│     └─┬ hawk@6.0.2
│       └── sntp@2.1.0 
└─┬ firebase-admin@5.8.2
  └─┬ @google-cloud/firestore@0.11.2
    └─┬ @google-cloud/common-grpc@0.5.5
      └─┬ grpc@1.7.3
        └─┬ node-pre-gyp@0.6.39
          └─┬ hawk@3.1.3
            └── sntp@1.0.9 
```

But in either case, your setup has been installed with an incompatible version of `sntp` -- some version that uses `async` support which is only available in Node.js 7 and up. I'm running Node.js 6 on my environment, and it installs a compatible version.

From `node_modules/sntp/lib/index.js`:
```
     16 exports.time = function (options, callback) {
     17 
     18     if (arguments.length !== 2) {
     19         callback = arguments[0];
     20         options = {};
     21     }
     22 
     23     const settings = Hoek.clone(options);
     24     settings.host = settings.host || 'time.google.com';
     25     settings.port = settings.port || 123;
     26     settings.resolveReference = settings.resolveReference || false;
```

Notice how there are no `async` keywords anywhere.

**Comment by enricribas** [comment]
Thank you, I apologize, seems the issue is with sendgrid. I removed 'sendgrid' and left 'sendgrid/@mail' and was able to deploy to firebase. 

I wonder if @hiranya911 is also using sendgrid?

**Comment by enricribas** [comment]
ok, closing, removing sendgrid solved my problem.
