### ISSUE TITLE
Windows - FirebaseAppCheckError: App attestation failed.

### ISSUE THREAD

**Issue by DavidDomkar** [firebase/firebase-admin-node#2308]
### Environment

  * Operating System version: Windows 11
  * Firebase SDK version: "firebase-admin": "^11.10.1"
  * Firebase Product: appcheck
  * Node.js version: 18.17.0
  * NPM version: 9.6.7

### Problem description

When trying to use firebase admin SDK to generate custom appcheck token, the code throws the following exception:

```
FirebaseAppCheckError: App attestation failed.
    at AppCheckApiClient.toFirebaseError (C:\Users\David\Projects\temp\node_modules\firebase-admin\lib\app-check\app-check-api-client-internal.js:150:16)
    at C:\Users\David\Projects\temp\node_modules\firebase-admin\lib\app-check\app-check-api-client-internal.js:72:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errorInfo: {
    code: 'app-check/permission-denied',
    message: 'App attestation failed.'
  },
  codePrefix: 'app-check'
}
```

This happens on my PC (Windows 11) and my laptop (Windows 11). However, it does not happen on my colleague's MacOS machine. The Firebase configuration was exactly the same on all these machines. I tried everything from switching node and dependency versions to tracing token requests with Wireshark to see the issue, but I just lost 3 whole days trying to fix this with no positive outcome. I seek any help I can. 

#### Steps to reproduce:

I made a simple reproduction repo where the problem occurs: https://github.com/DavidDomkar/firebase-admin-app-check-create-token-bug

- You will need to create `.env` file based on `.env.example` and fill in the `FIREBASE_APP_ID` based on your project. Also, `service-account.json` file must be copied over to the repository root.
- Then run `yarn install && yarn tsc && node lib/index.js` to run the example and see the error.

Relevant Code:

```ts
import { initializeApp } from "firebase-admin/app";
import { getAppCheck } from "firebase-admin/app-check";

async function main() {
  const app = initializeApp();
  const appCheck = getAppCheck(app);
  const token = await appCheck.createToken(process.env.FIREBASE_APP_ID);
  console.log(token);
}

main();
```

**Comment by DavidDomkar** [comment]
Hi @lahirumaramba. Thank you for your suggestions, but the credentials are correct. They are supplied, have valid signatures, and are for the project I am using. I tried with different projects and different credentials to be sure. This also seems to affect only Windows, on MacOS, for example, the reproduction works. Only on my two Windows machines, it does not.

Maybe my recent observation can help - the issue recently disappeared for a few days, and then it appeared again. My guess is that when I am working on my project for the first time, a new app check token is issued fine, but when I do not work on it for some time and return to it, this issue appears. My guess is that the node HTTP layer on Windows is somehow caching the old token, which was used to fetch the app check token without using a new one. It is strange, but this is the only reasonable explanation for why this happens. It would also explain why it started working again after a few days - the cache expired. And now it does not work again. I am not familiar with the inner workings of node, but I went as far as stepping through the SDK code with breakpoints and comparing requests externally with Wireshark. They are exactly the same on MacOS as on Windows, but one is working, and the other does not.

**Comment by Harshkanani** [comment]
@DavidDomkar I am using Custom Provider for protecting my firebase resources from abuse as I am not distributing my app through play store. I am facing similar issue. I checked my Service account permissions and confirmed that I have Firebase AppCheck Admin all permissions and I am able to use all other firebase services but getting permission denied error when creating Appcheck token. I am using Windows 11. Any solution?

**Exception**
`FirebaseAppCheckError: App attestation failed.
    at AppCheckApiClient.toFirebaseError (F:\Projects\2.9.0\TEST_APPCHECK\TestServer\node_modules\firebase-admin\lib\app-check\app-check-api-client-internal.js:150:16)
    at F:\Projects\2.9.0\TEST_APPCHECK\TestServer\node_modules\firebase-admin\lib\app-check\app-check-api-client-internal.js:72:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errorInfo: {
    code: 'app-check/permission-denied',
    message: 'App attestation failed.'
  },
  codePrefix: 'app-check'
}`

**Comment by DavidDomkar** [comment]
Hi @Harshkanani. Unfortunatelly, I am still experiencing the error and I don't have a solution. Since I am using windows only for development and there I am using app check debug token I can ignore the error. But it is really anoying and I cannot test production builds locally. I am still waiting for someone from Firebase to pick this up but since you and me are the only occurences I guess they just ignore it. As I have written before, I have tried a lot of things to mitigate this but none worked unfortunatelly. Only thing I observed is that sometimes the error goes away for a few days, but then appears again.

**Comment by ZiggyQubert** [comment]
I'm experiencing the same issue as well (I'm on a windows pc as well), one additional piece of information - sometimes it work correctly without any changes to code or data

**Comment by daviddomkar** [comment]
Would be great to have it fixed. Still experiencing it today.

**Comment by jdziek** [comment]
Hi. Im also experiencing this issue. The thing is that it's very erratic making it extremely difficult to debug. We suspect one of our customers is experiencing it too. In my particular case, we test different accounts in incognito mode where we follow a link supplied through an email. When the page first loads I get the "App attestation failed" error and I can't send requests to our backend due to an invalid appcheck token. I checked the requests and we do have an appcheck token which is weird. Even weirder, when I refresh the page, the appcheck works. We get a valid token, I can log in, send requests etc. Everything was fine till the beginning of April 2024, it just started happening recently, and as far as I know, it only happens to me and one customer. The customer is not using incognito. I would really appreciate any help.

**Comment by BenJackGill** [comment]
I am having the same issue on MacOs. Also some projects work and some don't.

**Comment by hansdaapurba** [comment]
This is a legit issue. I created a token with firebase-admin. When tried to create another token with longer expiry time, got the error and been stuck since then. Might have something to do with Firebase's security measures.
