### ISSUE TITLE
Got 'INTERNAL ASSERT FAILED: Unable to get project config' error when use Emulator

### ISSUE THREAD

**Issue by comicat-hu** [firebase/firebase-admin-node#2461]
### [READ] Step 1: Are you in the right place?

  * For issues related to __the code in this repository__ file a Github issue.
  * If the issue pertains to Cloud Firestore, read the instructions in the "Firestore issue"
    template.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS 12.4
  * Firebase SDK version: v11.11.1
  * Firebase Product: auth (auth, database, storage, etc)
  * Node.js version: v18.18.2
  * NPM version: v.9.8.1

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:

export FIREBASE_AUTH_EMULATOR_HOST="127.0.0.1:9099"

```js
import { initializeApp } from "firebase-admin/app";
import { getAuth } from "firebase-admin/auth";

const app = initializeApp({
  projectId: 'xxxxx',
});

const run = async () => {
    const projectConfigManager = getAuth(app).projectConfigManager();
    const projectConfig = await projectConfigManager.getProjectConfig();
};

run();
```

Got error when getProjectConfig with local emulator

```console
FirebaseAuthError: INTERNAL ASSERT FAILED: Unable to get project config
    at /xxx/node_modules/firebase-admin/lib/auth/auth-api-request.js:1658:15
    at /xxx/node_modules/firebase-admin/lib/auth/auth-api-request.js:1615:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run {
  errorInfo: {
    code: 'auth/internal-error',
    message: 'INTERNAL ASSERT FAILED: Unable to get project config'
  },
  codePrefix: 'auth'
}
```

It seems to be missing the config name field in the response ?

**Comment by nerder** [comment]
Same for `updateProjectConfig`

**Comment by mexican-jack** [comment]
i have the same issue when attempting to set a password policy
