### ISSUE TITLE
Deployments Suddenly Failing: `GLIBCXX_3.4.21' not found (required by firebase-admin)

### ISSUE THREAD

**Issue by boon4376** [firebase/firebase-admin-node#272]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MAC OS 10.13.4_____
  * Firebase SDK version:
- "firebase": "^5.0.2",
- "firebase-admin": "^5.12.1",
- "firebase-functions": "^1.0.2",
- "@firebase/app": "^0.3.1",
- "@firebase/firestore": "^0.5.2",

  * Firebase Product: Deployment error indicates firebase-admin

### [REQUIRED] Step 3: Describe the problem
Deployment Error

#### Steps to reproduce:

What happened? How can we make the problem occur?
Deploying firebase functions.. All functions suddenly failing even after no code changes. Did update many packages yesterday. Were deploying fine until this morning. ( I made code changes that did not involve any of the functions, but also tested reverting those changes to when it was last working )... Wondering if this is a server-side deployment issue?  

This could be a description, log/console output, etc.
```
⚠  functions[processDeleteUser]: Deployment error.
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /user_code/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
⚠  functions[adminapi]: Deployment error.
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /user_code/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
⚠  functions[query]: Deployment error.
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /user_code/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
⚠  functions[setupNewUser]: Deployment error.
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /user_code/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
⚠  functions[userApi]: Deployment error.
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /user_code/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
⚠  functions[scapp]: Deployment error.
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /user_code/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
⚠  functions[foodDetail]: Deployment error.
Function load error: Code in file index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /user_code/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
```

**Debug Log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy:staging:test' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'predeploy:staging:test',
4 verbose run-script   'deploy:staging:test',
4 verbose run-script   'postdeploy:staging:test' ]
5 info lifecycle strict-chef-webapp@2.0.0~predeploy:staging:test: strict-chef-webapp@2.0.0
6 info lifecycle strict-chef-webapp@2.0.0~deploy:staging:test: strict-chef-webapp@2.0.0
7 verbose lifecycle strict-chef-webapp@2.0.0~deploy:staging:test: unsafe-perm in lifecycle true
8 verbose lifecycle strict-chef-webapp@2.0.0~deploy:staging:test: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/matt/repos/strict-chef-webapp/node_modules/.bin:/Users/matt/repos/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle strict-chef-webapp@2.0.0~deploy:staging:test: CWD: /Users/matt/repos/strict-chef-webapp
10 silly lifecycle strict-chef-webapp@2.0.0~deploy:staging:test: Args: [ '-c',
10 silly lifecycle   'firebase use staging && node_modules/.bin/firebase functions:config:set environment.setting=\'test\' && cd functions && firebase functions:config:get>.runtimeconfig.json && cd ../ && NODE_ENV=test webpack --config webpack.config.dev.js --progress && node_modules/.bin/firebase deploy' ]
11 silly lifecycle strict-chef-webapp@2.0.0~deploy:staging:test: Returned: code: 1  signal: null
12 info lifecycle strict-chef-webapp@2.0.0~deploy:staging:test: Failed to exec deploy:staging:test script
13 verbose stack Error: strict-chef-webapp@2.0.0 deploy:staging:test: `firebase use staging && node_modules/.bin/firebase functions:config:set environment.setting='test' && cd functions && firebase functions:config:get>.runtimeconfig.json && cd ../ && NODE_ENV=test webpack --config webpack.config.dev.js --progress && node_modules/.bin/firebase deploy`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid strict-chef-webapp@2.0.0
15 verbose cwd /Users/matt/repos/strict-chef-webapp
16 verbose Darwin 17.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy:staging:test"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error strict-chef-webapp@2.0.0 deploy:staging:test: `firebase use staging && node_modules/.bin/firebase functions:config:set environment.setting='test' && cd functions && firebase functions:config:get>.runtimeconfig.json && cd ../ && NODE_ENV=test webpack --config webpack.config.dev.js --progress && node_modules/.bin/firebase deploy`
22 error Exit status 1
23 error Failed at the strict-chef-webapp@2.0.0 deploy:staging:test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by hiranya911** [comment]
This issue, the gRPC issue and the disruption recorded in the Firebase dashboard all seem to be related.  gRPC team has pulled the 1.12.0 distribution from npmjs.org. Can somebody verify if that helps alleviate the problem?

**Comment by eharango** [comment]
I still have the problem with `firebase-admin: 5.12.1` works fine with` firebase-admin: 5.12.0`

**Comment by hiranya911** [comment]
5.12.1 uses the latest version of Firestore. @eharango when does the error occur? When deploying a function?

@schmidt-sebastian FYI.

**Comment by eharango** [comment]
@hiranya911 sorry for the late response. The error occurs when I try to run `firebase deploy --only functions` locally Ubuntu 18.04 with `firebase-admin: 5.12.1`

**Comment by hiranya911** [comment]
@laurenzlong @schmidt-sebastian any idea what could be causing this?

@eharango I'd also recommend dropping your node_modules directory and any package lock files and rebuilding the project from the scratch.

**Comment by laurenzlong** [comment]
This was an incident yesterday and should be resolved now. If you're still experiencing issues, try deleting the node_modules folder locally before deploying again:

```
rm -rf node_modules # run inside functions folder
firebase deploy --only functions
```

**Comment by eharango** [comment]
@hiranya911  @laurenzlong I've done the test again with `firebase-admin: 5.12.1`, it's resolved, thanks guys
