### ISSUE TITLE
Firebase deploy fails due to grpc dependency in firebase-admin

### ISSUE THREAD

**Issue by dbartel** [firebase/firebase-admin-node#273]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS 10.13.4
  * Firebase SDK version: 5.12.0
  * Library version: 5.12.0
  * Firebase Product: functions 

#### Steps to reproduce:

1. Run ```firebase deploy --only functions```

Expected Behavior: functions get deployed

Actual: The following gets logged

```
  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
✔  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (37.82 KB) for uploading
✔  functions: functions folder uploaded successfully
i  functions: updating function statusFunction...
⚠  functions[statusFunction]: Deployment error.
Function load error: Code in file lib/index.js can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /user_code/node_modules/firebase-admin/node_modules/grpc/src/node/extension_binary/node-v48-linux-x64-glibc/grpc_node.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/grpc/src/grpc_extension.js:32:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
```

#### Relevant Code:

I can't tell if this is a bug in firebase-admin, a bug in grpc-node, a bug with npm, or just weird configuration issues on my machine.

firebase-admin appears to be trying to pull the wrong binary for grpc.

Running `npm rebuild grpc --update-binary` gives me this:

```
> grpc@1.12.0 install /Users/daniel.bartel/projects/cooks/server-cooks-functions/functions/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/Users/daniel.bartel/projects/cooks/server-cooks-functions/functions/node_modules/grpc/src/node/extension_binary/node-v48-darwin-x64-unknown/grpc_node.node" is installed via remote
grpc@1.12.0 /Users/daniel.bartel/projects/cooks/server-cooks-functions/functions/node_modules/grpc
```

Note the *node-v48-darwin-x64-unknown* instead of *node-v48-linux-x64-glibc* that firebase-admin is looking for

**Comment by dbartel** [comment]
Duplicate of #272, I'll close this out
