### ISSUE TITLE
Firestore access via Firebase-admin crashes due to nanomatch/micromatch property error

### ISSUE THREAD

**Issue by sharanan** [firebase/firebase-admin-node#298]
All calls to firestore via firebase-admin sdk fail with the following reason:-

TypeError: Cannot read property 'addQmark' of undefined
    at Object.<anonymous> (/user_code/node_modules/firebase-admin/node_modules/nanomatch/lib/compilers.js:92:15)
    at Object.visit (/user_code/node_modules/firebase-admin/node_modules/snapdragon/lib/compiler.js:129:15)
    at Object.mapVisit (/user_code/node_modules/firebase-admin/node_modules/snapdragon/lib/compiler.js:143:12)
    at Object.compile (/user_code/node_modules/firebase-admin/node_modules/snapdragon/lib/compiler.js:168:10)
    at Snapdragon.compile (/user_code/node_modules/firebase-admin/node_modules/snapdragon/index.js:156:32)
    at /user_code/node_modules/firebase-admin/node_modules/micromatch/index.js:786:23
    at memoize (/user_code/node_modules/firebase-admin/node_modules/micromatch/index.js:859:13)
    at Function.micromatch.compile (/user_code/node_modules/firebase-admin/node_modules/micromatch/index.js:783:10)
    at create (/user_code/node_modules/firebase-admin/node_modules/micromatch/index.js:686:25)
    at /user_code/node_modules/firebase-admin/node_modules/micromatch/index.js:695:16

  * Firebase SDK version: 3.18.5
  * Firebase Functions version: 1.1.0
  * Firebase Admin version: 5.12.1

**Comment by jonschlinkert** [comment]
It appears that firebase-admin is using a buggy version of nanomatch that was reverted right after the issue was created. 

Please see https://github.com/micromatch/nanomatch/issues/15 for more details.

**Comment by amay077** [comment]
Is it fixed?
I can not facing this error when re-deploy my function to Firebase.

**Comment by jonschlinkert** [comment]
Please see micromatch/nanomatch#15 for updates.

**Comment by roger199585** [comment]
I still have the same bug after I delete package-lock and node_modules, and then reinstall the npm modules. What is the version of firebase-admin firebase-functions of your project?

**Comment by sharanan** [comment]
Firebase Functions version: 1.1.0
Firebase Admin version: 5.12.1

**Comment by DaAsfaha** [comment]
Still left with the same bug. Updated everything to the versions @sharanan mentioned.
Pretty frustrating tbh

**Comment by jonschlinkert** [comment]
If it is indeed the same issue, it’s resolved by simply reinstalling dependencies.
