### ISSUE TITLE
Error: Can't determine Firebase Database URL. Upgrading functions to v1

### ISSUE THREAD

**Issue by piuccio** [firebase/firebase-admin-node#299]
* Operating System version: OS X
  * Firebase Admin version: 5.12.1
  * Firebase functions version: 1.1.0
  * Firebase tools version: 3.19.1
  * Firebase Product: database

### Steps to reproduce

I'm trying to upgrade to firebase functions version 1 and I need to use service accounts to mint my custom tokens.

When I initialize the app with

```js
admin.initializeApp();
```

most functions work ok, except the one that needs token, this will be eventually fixed (?) by #285, in the mean time, the documentation suggests using service accounts, but when I run

```js
admin.initializeApp({
  credential: admin.credential.cert(account),
  projectId: process.env.FIREBASE_CONFIG.projectId,
  databaseURL: process.env.FIREBASE_CONFIG.databaseURL,
  storageBucket: process.env.FIREBASE_CONFIG.storageBucket,
});

admin.database();
```

I get the exception

```
Error: Can't determine Firebase Database URL.
    at FirebaseDatabaseError.Error (native)
    at FirebaseDatabaseError.FirebaseError [as constructor] (/user_code/node_modules/firebase-admin/lib/utils/error.js:39:28)
    at new FirebaseDatabaseError (/user_code/node_modules/firebase-admin/lib/utils/error.js:190:23)
    at DatabaseService.ensureUrl (/user_code/node_modules/firebase-admin/lib/database/database.js:75:15)
    at DatabaseService.getDatabase (/user_code/node_modules/firebase-admin/lib/database/database.js:52:26)
    at FirebaseApp.database (/user_code/node_modules/firebase-admin/lib/firebase-app.js:231:24)
    at FirebaseNamespace.fn (/user_code/node_modules/firebase-admin/lib/firebase-namespace.js:280:45)
    at functions.https.onRequest.withCors (/user_code/utils/request-wrapper.js:38:23)
    at cors (/user_code/utils/request-helpers.js:53:9)
    at cors (/user_code/node_modules/cors/lib/index.js:188:7)
    at /user_code/node_modules/cors/lib/index.js:224:17
    at origin (/user_code/utils/request-helpers.js:20:9)
    at /user_code/node_modules/cors/lib/index.js:219:13
    at optionsCallback (/user_code/node_modules/cors/lib/index.js:199:9)
    at corsMiddleware (/user_code/node_modules/cors/lib/index.js:204:7)
    at /user_code/utils/request-helpers.js:48:33
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:37:41)
    at /var/tmp/worker/worker.js:684:7
    at /var/tmp/worker/worker.js:668:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

I tried to use this as well

```js
const defaultApp = admin.initializeApp({
  credential: admin.credential.cert(account),
  projectId: process.env.FIREBASE_CONFIG.projectId,
  databaseURL: process.env.FIREBASE_CONFIG.databaseURL,
  storageBucket: process.env.FIREBASE_CONFIG.storageBucket,
});

admin.database(defaultApp);
```

but I get the same exception

Is database completely broken with service credentials?

**Comment by hiranya911** [comment]
`FIREBASE_CONFIG` contains a string. You have to parse it first. Please follow the examples at https://firebase.google.com/docs/functions/beta-v1-diff#functionsconfigfirebase_removed

Also report functions-related issues at https://github.com/firebase/firebase-functions
