### ISSUE TITLE
Error importing users: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by gabrielmoncea** [firebase/firebase-admin-node#327]
Just wrote a script for importing the users and it looks like this:

```
var admin = require('firebase-admin');

var serviceAccount = require('./file-with-credentials.json');

admin.initializeApp({
	credential: admin.credential.cert(serviceAccount),
        databaseURL: 'https://<<database-name>>.firebaseio.com'
});

var userRecords = [
  {
    uid: 'some-uid',
    displayName: 'John doe',
    email: 'email@example.com',
    passwordHash: Buffer.from('passwordHash1'),
    passwordSalt: Buffer.from('salt1')
  }
];

var userImportOptions = {
  hash: {
    algorithm: 'HMAC_SHA256',
    key: Buffer.from('secretKey')
  }
};

admin
        .auth()
        .importUsers(userRecords, userImportOptions)
	.then(function(results) {
		results.error.forEach(function(indexedError) {
			console.log('Error importing user ' + indexedError.index);
		});
	})
	.catch(function(error) {
		console.log('Error importing users:', error);
	});

```

And it throws me this error:
```
Error importing users: TypeError: Cannot read property 'forEach' of undefined
    at ~/Documents/admin.js:31:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by hiranya911** [comment]
Field is called `errors`, not `error`.

https://firebase.google.com/docs/reference/admin/node/admin.auth.UserImportResult
