### ISSUE TITLE
Admin SDK cannot authenticate when mocking Date global

### ISSUE THREAD

**Issue by nthgol** [firebase/firebase-admin-node#367]
### Step 2: Describe your environment

  * Operating System version: Windows 10 Home
  * Firebase SDK version: "firebase": "^5.4.2",
    "firebase-admin": "^5.12.0"
  * Library version: _____
  * Firebase Product: Admin SDK nodejs, firestore (auth, database, storage, etc)

### Step 3: Describe the problem
I am running Jest unit tests on functions including Admin SDK calls. Admin SDK is initialized with a JSON service account key **before tests are run**

using `npm install mockdate` package, which allows you to override the `global Date`, subsequent admin sdk calls provide the error below.

I would appreciate getting an understanding as to if this is a bug or something I can circumvent. 

#### Steps to reproduce:
```
MockDate.set(moment().add(1, 'hours').toISOString());
admin.firestore().collection('some collection').doc('some doc').get()
```

#### Relevant Errors:

```
 { Error: 16 UNAUTHENTICATED: Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
        at Object.<anonymous>.exports.createStatusError (...\node_modules\grpc\src\common.js:87:15)
        at ClientReadableStream._emitStatusIfDone (...\node_modules\grpc\src\client.js:235:26)
        at ClientReadableStream._receiveStatus (....\node_modules\grpc\src\client.js:213:8)
        at Object.onReceiveStatus (....\node_modules\grpc\src\client_interceptors.js:1256:15)
        at InterceptingListener.Object.<anonymous>.InterceptingListener._callNext (.....\node_modules\grpc\src\client_interceptors.js:564:42)
        at InterceptingListener.Object.<anonymous>.InterceptingListener.onReceiveStatus (....\node_modules\grpc\src\client_interceptors.js:614:8)
        at ....\node_modules\grpc\src\client_interceptors.js:1019:24
      code: 16,
      metadata: Metadata { _internal_repr: { 'www-authenticate': [Array] } },
      details: 'Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.' }
```

**Comment by hiranya911** [comment]
Google auth servers will not issue ID tokens when the client's clock is out of sync. This approach of testing does not sound correct. You probably need to mock out all RPC calls made by the SDKs during testing.
