### ISSUE TITLE
 DEADLINE_EXCEEDED: Deadline Exceeded

### ISSUE THREAD

**Issue by atappz** [firebase/firebase-admin-node#452]
**Describe your environment**
    Operating System : Ubuntu
    Firebase Product: Firestore

**Error log** 
(node:12756) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27179)
(node:12756) UnhandledPromiseRejectionWarning: Error: 4 DEADLINE_EXCEEDED: Deadline Exceeded
    at Object.exports.createStatusError (/usr/local/FundMgmnt/cron/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/usr/local/FundMgmnt/cron/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/usr/local/FundMgmnt/cron/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/usr/local/FundMgmnt/cron/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/usr/local/FundMgmnt/cron/node_modules/grpc/src/client_interceptors.js:845:24)
 I receive this errors at catch.

**Comment by zubair-0** [comment]
Hey there @atappz, theres a Deadline Exceeded issue [https://github.com/firebase/firebase-admin-node/issues/349](url) already opened.
You might wanna look at that and close this issue if you think that issue is similar to yours. You can elaborate on your error by adding some statements like
- when does it occur on read or write 
- how much docs are you writing or reading
- whats the size of the document

To make sure you are not exceeding limits, you can look at [https://firebase.google.com/docs/firestore/quotas](url)

**Comment by wilhuff** [comment]
Closing for lack of activity.

**Comment by pmohun** [comment]
Hello, 

I'd like to reopen this issue. 

During a batch write operation I am receiving this error code.

**Comment by wilhuff** [comment]
The best course of action at this point is to open a new issue, including all the details of a new issue, including what you’re trying to do, how we can reproduce your problem, etc.
