### ISSUE TITLE
All of the read action throw errors

### ISSUE THREAD

**Issue by Oskang09** [firebase/firebase-admin-node#454]
Any read action will throw these error.

  * Operating System version: Ubuntu 18.04
  * Firebase SDK version: 7.0.0
  * Node version : 8.10.0 & 11.4.0
  * Firebase Product: Cloud Firestore

**Update 16/2/2019**

Found some problem *maybe
1) Different repo installed same version of firebase-admin but in folder have different files
2) package.json of it also different ( _phantomChildren: [] )

Most of the errors cause by 
1) Readable-stream ( so i guess missing this. )

Tried ways to fix
1) Clean cache & node_modules and `npm install` again
2) Changing different node version to run it
3) Upgrade to latest npm and re-run way 1.
4) Tried install latest library that cause error.

Update & onSnapshot() 
```
Firestore (1.0.1) 2019-02-11T14:33:59.014Z ##### [Firestore]: Initialized Firestore GAPIC Client
Firestore (1.0.1) 2019-02-11T14:33:59.016Z N4rQ2 [Firestore.request]: Sending request: {"database":"projects/allder-687d0/databases/(default)"}
Firestore (1.0.1) 2019-02-11T14:34:00.051Z N4rQ2 [Firestore.request]: Received response: {"transaction":{"type":"Buffer","data":[17,217,205,53,228,236,173,210,95,34,89,0,153,25,48,44,58,233,161,118,62,90,58,175,70,8,139,146,156,7,181,183,147,132,199,83,29,61,65,63,98,198,200,27,235,94,43,88,120,93,133,17,141,99,74,248,137,152,139,10,16,225,226,138,155,42,190,94,112,227,223,210,104,201,237,0,243,207,232,249,158,157,209,163,8,226,255,17,249,45,84,64,4,134,197,221,188,34,239,95]}}
Firestore (1.0.1) 2019-02-11T14:34:00.074Z N4rQ2 [WriteBatch.commit]: Sending 1 writes
Firestore (1.0.1) 2019-02-11T14:34:00.076Z N4rQ2 [Firestore.request]: Sending request: {"database":"projects/allder-687d0/databases/(default)","writes":[{"update":{"name":"projects/allder-687d0/databases/(default)/documents/1/status","fields":{"1":{"mapValue":{"fields":{"PAX":{"integerValue":1},"EMPTY":{"booleanValue":true},"PROGRESS":{"booleanValue":false},"PAID":{"booleanValue":false}}}},"2":{"mapValue":{"fields":{"PAX":{"integerValue":2},"EMPTY":{"booleanValue":true},"PROGRESS":{"booleanValue":false},"PAID":{"booleanValue":false}}}},"3":{"mapValue":{"fields":{"PAX":{"integerValue":3},"EMPTY":{"booleanValue":true},"PROGRESS":{"booleanValue":false},"PAID":{"booleanValue":false}}}},"4":{"mapValue":{"fields":{"PAX":{"integerValue":5},"EMPTY":{"booleanValue":true},"PROGRESS":{"booleanValue":false},"PAID":{"booleanValue":false}}}},"5":{"mapValue":{"fields":{"PAX":{"integerValue":3},"EMPTY":{"booleanValue":true},"PROGRESS":{"booleanValue":false},"PAID":{"booleanValue":false}}}},"6":{"mapValue":{"fields":{"PAX":{"integerValue":3},"EMPTY":{"booleanValue":true},"PROGRESS":{"booleanValue":false},"PAID":{"booleanValue":false}}}}}},"updateMask":{"fieldPaths":["`1`.EMPTY","`1`.PAID","`1`.PAX","`1`.PROGRESS","`2`.EMPTY","`2`.PAID","`2`.PAX","`2`.PROGRESS","`3`.EMPTY","`3`.PAID","`3`.PAX","`3`.PROGRESS","`4`.EMPTY","`4`.PAID","`4`.PAX","`4`.PROGRESS","`5`.EMPTY","`5`.PAID","`5`.PAX","`5`.PROGRESS","`6`.EMPTY","`6`.PAID","`6`.PAX","`6`.PROGRESS"]}}],"transaction":{"type":"Buffer","data":[17,217,205,53,228,236,173,210,95,34,89,0,153,25,48,44,58,233,161,118,62,90,58,175,70,8,139,146,156,7,181,183,147,132,199,83,29,61,65,63,98,198,200,27,235,94,43,88,120,93,133,17,141,99,74,248,137,152,139,10,16,225,226,138,155,42,190,94,112,227,223,210,104,201,237,0,243,207,232,249,158,157,209,163,8,226,255,17,249,45,84,64,4,134,197,221,188,34,239,95]}}
Firestore (1.0.1) 2019-02-11T14:34:00.092Z e8OAy [Firestore.readWriteStream]: Opening stream
Firestore (1.0.1) 2019-02-11T14:34:00.096Z e8OAy [Firestore._initializeStream]: Sending request: {"database":"projects/allder-687d0/databases/(default)","addTarget":{"documents":{"documents":["projects/allder-687d0/databases/(default)/documents/1/status"]},"targetId":1}}
Firestore (1.0.1) 2019-02-11T14:34:00.101Z e8OAy [Firestore._retry]: Retrying request that failed with error: TypeError: Cannot read property 'ended' of undefined
    at BunWrapper.Writable.write (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/readable-stream/lib/_stream_writable.js:191:13)
    at Promise (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:927:22)
    at new WrappedPromise (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at Firestore._initializeStream (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:872:16)
    at Promise.resolve.then (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:1047:33)
    at propagateAslWrapper (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:504:23)
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:541:70
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31
Firestore (1.0.1) 2019-02-11T14:34:00.201Z e8OAy [Firestore.readWriteStream]: Opening stream
Firestore (1.0.1) 2019-02-11T14:34:00.203Z e8OAy [Firestore._initializeStream]: Sending request: {"database":"projects/allder-687d0/databases/(default)","addTarget":{"documents":{"documents":["projects/allder-687d0/databases/(default)/documents/1/status"]},"targetId":1}}
Firestore (1.0.1) 2019-02-11T14:34:00.205Z e8OAy [Firestore._retry]: Retrying request that failed with error: TypeError: Cannot read property 'ended' of undefined
    at BunWrapper.Writable.write (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/readable-stream/lib/_stream_writable.js:191:13)
    at Promise (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:927:22)
    at new WrappedPromise (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at Firestore._initializeStream (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:872:16)
    at Promise.resolve.then (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:1047:33)
    at propagateAslWrapper (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:504:23)
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:541:70
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31
Firestore (1.0.1) 2019-02-11T14:34:00.306Z e8OAy [Firestore.readWriteStream]: Opening stream
Firestore (1.0.1) 2019-02-11T14:34:00.306Z e8OAy [Firestore._initializeStream]: Sending request: {"database":"projects/allder-687d0/databases/(default)","addTarget":{"documents":{"documents":["projects/allder-687d0/databases/(default)/documents/1/status"]},"targetId":1}}
Firestore (1.0.1) 2019-02-11T14:34:00.307Z e8OAy [Firestore._retry]: Retrying request that failed with error: TypeError: Cannot read property 'ended' of undefined
    at BunWrapper.Writable.write (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/readable-stream/lib/_stream_writable.js:191:13)
    at Promise (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:927:22)
    at new WrappedPromise (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at Firestore._initializeStream (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:872:16)
    at Promise.resolve.then (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:1047:33)
    at propagateAslWrapper (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:504:23)
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:541:70
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31
Firestore (1.0.1) 2019-02-11T14:34:00.407Z e8OAy [Firestore.readWriteStream]: Opening stream
Firestore (1.0.1) 2019-02-11T14:34:00.409Z e8OAy [Firestore._initializeStream]: Sending request: {"database":"projects/allder-687d0/databases/(default)","addTarget":{"documents":{"documents":["projects/allder-687d0/databases/(default)/documents/1/status"]},"targetId":1}}
Firestore (1.0.1) 2019-02-11T14:34:00.410Z e8OAy [Firestore._retry]: Retrying request that failed with error: TypeError: Cannot read property 'ended' of undefined
    at BunWrapper.Writable.write (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/readable-stream/lib/_stream_writable.js:191:13)
    at Promise (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:927:22)
    at new WrappedPromise (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at Firestore._initializeStream (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:872:16)
    at Promise.resolve.then (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:1047:33)
    at propagateAslWrapper (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:504:23)
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:541:70
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31
Firestore (1.0.1) 2019-02-11T14:34:00.486Z N4rQ2 [Firestore.request]: Received response: {"writeResults":[{"transformResults":[],"updateTime":{"seconds":"1549880794","nanos":452517000}}],"commitTime":{"seconds":"1549895639","nanos":655975000}}
Firestore (1.0.1) 2019-02-11T14:34:00.512Z e8OAy [Firestore.readWriteStream]: Opening stream
Firestore (1.0.1) 2019-02-11T14:34:00.513Z e8OAy [Firestore._initializeStream]: Sending request: {"database":"projects/allder-687d0/databases/(default)","addTarget":{"documents":{"documents":["projects/allder-687d0/databases/(default)/documents/1/status"]},"targetId":1}}
Firestore (1.0.1) 2019-02-11T14:34:00.513Z e8OAy [Firestore._retry]: Request failed with error: TypeError: Cannot read property 'ended' of undefined
    at BunWrapper.Writable.write (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/readable-stream/lib/_stream_writable.js:191:13)
    at Promise (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:927:22)
    at new WrappedPromise (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at Firestore._initializeStream (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:872:16)
    at Promise.resolve.then (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/index.js:1047:33)
    at propagateAslWrapper (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:504:23)
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:541:70
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31
(node:18717) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'corked' of undefined
    at DestroyableTransform.Writable.end (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/readable-stream/lib/_stream_writable.js:561:13)
    at closeStream (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/@google-cloud/firestore/build/src/watch.js:306:20)
    at Promise.propagateAslWrapper (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:504:23)
    at Promise.__asl_wrapper (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31)
    at proxyWrapper (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:529:23)
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/index.js:541:70
    at /home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/async-listener/glue.js:188:31
(node:18717) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejectinga promise which was not handled with .catch(). (rejection id: 8)
(node:18717) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Transaction Query 
```
Firestore (1.0.1) 2019-02-11T14:31:20.129Z ##### [Firestore]: Initialized Firestore GAPIC Client
Firestore (1.0.1) 2019-02-11T14:31:20.131Z kwgKd [Firestore.request]: Sending request: {"database":"projects/allder-687d0/databases/(default)"}
Firestore (1.0.1) 2019-02-11T14:31:21.615Z kwgKd [Firestore.request]: Received response: {"transaction":{"type":"Buffer","data":[17,97,229,78,111,124,159,130,150,34,89,0,153,25,48,44,0,118,176,156,50,74,5,211,146,91,98,182,132,4,219,174,233,16,155,194,11,29,117,237,251,49,176,87,231,190,171,64,231,247,82,5,64,95,122,13,128,186,111,57,29,132,202,45,85,153,24,1,162,31,218,235,43,17,107,45,131,64,245,243,117,243,109,159,195,189,62,166,122,143,146,145,46,162,61,204,103,45,27,247]}}
RUNNING TSQL
Firestore (1.0.1) 2019-02-11T14:31:21.618Z kwgKd [Firestore.readStream]: Sending request: {"database":"projects/allder-687d0/databases/(default)","transaction":{"type":"Buffer","data":[17,97,229,78,111,124,159,130,150,34,89,0,153,25,48,44,0,118,176,156,50,74,5,211,146,91,98,182,132,4,219,174,233,16,155,194,11,29,117,237,251,49,176,87,231,190,171,64,231,247,82,5,64,95,122,13,128,186,111,57,29,132,202,45,85,153,24,1,162,31,218,235,43,17,107,45,131,64,245,243,117,243,109,159,195,189,62,166,122,143,146,145,46,162,61,204,103,45,27,247]},"documents":["projects/allder-687d0/databases/(default)/documents/1/1"]}
/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/readable-stream/lib/_stream_writable.js:288
  var isBuf = !state.objectMode && _isUint8Array(chunk);
                     ^

TypeError: Cannot read property 'objectMode' of undefined
    at DestroyableTransform.Writable.write (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/readable-stream/lib/_stream_writable.js:288:22)
    at StreamProxy.ondata (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at StreamProxy.emit (events.js:189:13)
    at addChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at StreamProxy.Readable.push (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at StreamProxy.Duplexify._forward (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/index.js:170:26)
    at DestroyableTransform.onreadable (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/index.js:134:10)
    at DestroyableTransform.emit (events.js:189:13)
    at emitReadable_ (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:504:10)
    at emitReadable (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:498:62)
    at addChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:298:29)
    at readableAddChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DestroyableTransform.afterTransform (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:91:10)
    at DestroyableTransform.noop [as _transform] (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:189:13)
    at addChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:148:32)
```

Read Query ( firestore.doc("1/status").get() )
```
Firestore (1.0.1) 2019-02-11T14:22:16.545Z ##### [Firestore]: Initialized Firestore GAPIC Client
Firestore (1.0.1) 2019-02-11T14:22:16.547Z GsuVR [Firestore.readStream]: Sending request: {"parent":"projects/allder-687d0/databases/(default)/documents","structuredQuery":{"from":[{"collectionId":"1"}]}}
/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/readable-stream/lib/_stream_writable.js:288
  var isBuf = !state.objectMode && _isUint8Array(chunk);
                     ^

TypeError: Cannot read property 'objectMode' of undefined
    at DestroyableTransform.Writable.write (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/firebase-admin/node_modules/readable-stream/lib/_stream_writable.js:288:22)
    at StreamProxy.ondata (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at StreamProxy.emit (events.js:189:13)
    at addChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at StreamProxy.Readable.push (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at StreamProxy.Duplexify._forward (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/index.js:170:26)
    at DestroyableTransform.onreadable (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/duplexify/index.js:134:10)
    at DestroyableTransform.emit (events.js:189:13)
    at emitReadable_ (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:504:10)
    at emitReadable (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:498:62)
    at addChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:298:29)
    at readableAddChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at DestroyableTransform.afterTransform (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:91:10)
    at DestroyableTransform.noop [as _transform] (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:189:13)
    at addChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/home/oskang09/Desktop/Git Repo/Ordo @ Backend/sails/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:148:32)
```

**Comment by Oskang09** [comment]
I'm check back mine some old codebase, using firebase-admin 6.0.0, its worked so i install back 6.0.0 and working well.

**Comment by wilhuff** [comment]
Could you send your package-lock.json or otherwise list out the versions of all the packages in your project? It seems as if you've somehow you've gotten an incompatible version of a dependency in there. I'm currently working on reproducing.

**Comment by Oskang09** [comment]
Here is it. I'm found that too same code, same version but in their folder have different thing. 

[package-lock.txt](https://github.com/firebase/firebase-admin-node/files/2870397/package-lock.txt)

**Comment by wilhuff** [comment]
I've tried both node v8.14.0 and v10.14.1 and can't reproduce the issue. Everything works as expected.

Looking through your package-lock.json nothing really stands out except that you have a _lot_ of dependencies in there that depend upon different versions of readable-stream. The stack trace points to files that I don't have 

Could you share your package.json?

**Comment by Oskang09** [comment]
Here is it.
[package.txt](https://github.com/firebase/firebase-admin-node/files/2871580/package.txt)

**Comment by hiranya911** [comment]
@wilhuff can you take a look?

**Comment by Oskang09** [comment]
totally this fixed ady by reinstalling all node_modules due to swapping from ubuntu to windows.
