### ISSUE TITLE
@firebase/app dependency is not installed together with firebase-admin

### ISSUE THREAD

**Issue by vpishuk** [firebase/firebase-admin-node#508]
* Google AppEngine
  * Firebase SDK version:7.3.0
  * Firebase Product: firebase-admin

#### Steps to reproduce:
I've updated the package to the latest version.
And then at logs in GCP I saw:
{ Error: Cannot find module '@firebase/app'
     at Function.Module._resolveFilename (module.js:548:15) A 
     at Function.Module._load (module.js:475:25) A 
     at Module.require (module.js:597:17) A 
     at require (internal/module.js:11:18) A 
     at Object.<anonymous> (/srv/node_modules/@firebase/database/dist/index.node.cjs.js:7:32) A 
     at Module._compile (module.js:653:30) A 
     at Object.Module._extensions..js (module.js:664:10) A 
     at Module.load (module.js:566:32) A 
     at tryModuleLoad (module.js:506:12) A 
     at Function.Module._load (module.js:498:3) code: 'MODULE_NOT_FOUND' } A 

My package.json file:
```
{
  "name": "name",
  "author": "author",
  "version": "2.0.5",
  "scripts": {
    "start": "node ./server",
    "start:dev": "nodemon ./server",
  },
  "devDependencies": {
    "cors": "2.8.4",
    "nodemon": "1.17.3",
  },
  "dependencies": {
    "@google-cloud/bigtable": "1.0.1",
    "@google-cloud/error-reporting": "0.6.3",
    "@google-cloud/pubsub": "0.28.1",
    "@google-cloud/storage": "2.5.0",
    "body-parser": "1.18.3",
    "compression": "1.7.4",
    "cookie-parser": "1.4.4",
    "ejs": "=2.6.1",
    "express": "=4.16.4",
    "firebase-admin": "7.3.0",
    "googleapis": "39.2.0",
    "moment": "2.24.0",
    "zip-stream": "=2.0.1"
  }
}

```

**Comment by hiranya911** [comment]
Not sure why this would happen. Do you know what version of Node and NPM get used in App Engine?

**Comment by hiranya911** [comment]
Closing this due to lack of activity. Let us know more details if you need us to take another look.
