### ISSUE TITLE
Error message/code not passed into error

### ISSUE THREAD

**Issue by Ivkaa** [firebase/firebase-admin-node#531]
* Operating System version: macos mojave 10.14.4
  * Firebase SDK version: latest - 7.3.0
  * Library version: 7.3.0 
* Firebase Product: auth

#### Steps to reproduce:
Call:
```await firebase.auth().verifySessionCookie(token, true);```
with invalid token
ex.
```await firebase.auth().verifySessionCookie("a", true);```

Which throws error
```
TypeError: Cannot read property 'code' of undefined
      at FirebaseAuthError.FirebaseError.toJSON (/Users/ewe/Projects/seasy/api/node_modules/firebase-admin/lib/utils/error.js:73:24)
      at JSON.stringify (<anonymous>)
      at prettyJSONStringify (/Users/ewe/Projects/seasy/api/node_modules/apollo-server-core/dist/runHttpQuery.js:258:17)
      at throwHttpGraphQLError (/Users/ewe/Projects/seasy/api/node_modules/apollo-server-core/dist/runHttpQuery.js:26:42)
      at Object.<anonymous> (/Users/ewe/Projects/seasy/api/node_modules/apollo-server-core/dist/runHttpQuery.js:66:28)
      at Generator.next (<anonymous>)
      at fulfilled (/Users/ewe/Projects/seasy/api/node_modules/apollo-server-core/dist/runHttpQuery.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```
(the code has line ```this.code``` and obviously `this === undefined`)

If I inspect value of errorInfo in FirebaseError
```
function FirebaseError(errorInfo) {
   console.log(errorInfo)
   ...rest of the code
}
```
the value contains the right error message and code, so the error is not being thrown as it should but instead there is the error above when handling the error
```
{ code: 'auth/argument-error',
  message:
   'Decoding Firebase session cookie failed. Make sure you passed the entire string JWT which represents a session cookie. See https://firebase.google.com/docs/auth/admin/manage-cookies for details on how to retrieve a session cookie.' }
```

**Comment by hiranya911** [comment]
Are you using some kind of a framework (I see appllo-server-core in the stacktrace)? This is most likely an issue in your environment or the framework. I tried the following code, and it works as expected:

```
const admin = require('firebase-admin');

admin.initializeApp();

async function runTest() {
  try {
    await admin.auth().verifySessionCookie('a', true);
  } catch (err) {
    console.log('Failed to verify: ', JSON.stringify(err));
  }
}

runTest();
```

Output:
```
Failed to verify:  {"code":"auth/argument-error","message":"Decoding Firebase session cookie failed. Make sure you passed the entire string JWT which represents a session cookie. See https://firebase.google.com/docs/auth/admin/manage-cookies for details on how to retrieve a session cookie."}
```

In your case the apollo-server-core tries to JSON stringify the error, but is not able to for some reason. Can you provide us a complete, minimal repro of this issue?

**Comment by hiranya911** [comment]
Closing due to lack of information.
