### ISSUE TITLE
api-request module not installed in utils

### ISSUE THREAD

**Issue by howardmalec** [firebase/firebase-admin-node#679]
```
alec$ sudo node parse_data_node.js 
module.js:549
    throw err;
    ^

Error: Cannot find module '../utils/api-request'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/alec/node_modules/firebase-admin/lib/auth/credential.js:24:21)

```

Added api-request to the /utils/ folder which seems to resolve the issue. However getting additional errors for other missing modules.

**Comment by howardmalec** [comment]
The package doesn't require updates. Needed to change ownership and write permissions for several directories. Here were the recommendations from yarn that resolved the challenge:

```
You should change the ownership of these directories to your user.
  sudo chown -R $(whoami) /usr/local/bin /usr/local/include /usr/local/lib /usr/local/share /usr/local/share/doc /usr/local/share/man /usr/local/share/man/man1

And make sure that your user has write permission.
  chmod u+w /usr/local/bin /usr/local/include /usr/local/lib /usr/local/share /usr/local/share/doc /usr/local/share/man /usr/local/share/man/man1

```
