### ISSUE TITLE
⚠  Error: Cannot find module 'firebase-admin'

### ISSUE THREAD

**Issue by Nicour** [firebase/firebase-admin-node#704]
Hello,

I am running my app locally and i am having this error:

"i Starting emulators: ["functions","hosting"]
? Your requested "node" version "8" doesn't match your global version "12"
? functions: Emulator started at http://localhost:5001
i hosting: Serving hosting files from: public
? hosting: Local server: http://localhost:5000
? hosting: Emulator started at http://localhost:5000
i functions: Watching "/Users/nico/Documents/nexow/nexow-api-firebase/functions" for Cloud Functions...
? Error: Cannot find module 'firebase-admin'
Require stack:
- /Users/nico/.nvm/versions/node/v12.6.0/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
at Function.Module._load (internal/modules/cjs/loader.js:527:27)
at Module.require (internal/modules/cjs/loader.js:683:19)
at Object.<anonymous> (/Users/nico/Documents/nexow/nexow-api-firebase/functions/node_modules/express-firebase-middleware/lib/auth.middleware.js:10:26)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:643:32)
at Function.Module._load (internal/modules/cjs/loader.js:556:12)
at Module.require (internal/modules/cjs/loader.js:683:19)
at require (internal/modules/cjs/helpers.js:16:16)
? We were unable to load your functions code. (see above)"

I've already done all the NPM installs, but no way...
A few hours ago it worked and recently stop working. My partner is running the same code and it works for him.
I tryed try deleting first both the 'package-lock.json' file and the 'node_modules' folder before running the npm install command again but don´t work.

Do anyone know where is the problem?

Thank you

**Comment by hiranya911** [comment]
SO is the right forum for this type of questions: https://stackoverflow.com/questions/58841887/firebase-cannot-found-the-firebase-admin-module-when-run-firebase-serve

**Comment by ltnilaysahu** [comment]
I am facing the same issue still. Inspite of doing npm-install , on npm start, firebase-admin cannot be found.
