### ISSUE TITLE
[Firestore]: GOAWAY and DEADLINE_EXCEEDED errors on Firestore writes 

### ISSUE THREAD

**Issue by shaibt** [firebase/firebase-admin-node#731]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: GAE Flex node
  * Firebase SDK version: 8.8.0
  * Firebase Product: Firestore
  * Node.js version:  8.15.1
  * NPM version: _____

### [REQUIRED] Step 3: Describe the problem

Have been recently plagued by errors generated by the underlying grpc layer of the firestore client.
Each and every of my production servers gets this error at some point after a few days of running:
```
(node:17) UnhandledPromiseRejectionWarning: Error [ERR_HTTP2_GOAWAY_SESSION]: New streams cannot be created after receiving a GOAWAY
  at ClientHttp2Session.request (internal/http2/core.js:1424:13)
  at Subchannel.startCallStream (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/subchannel.js:326:42)
  at callStream.filterStack.sendMetadata.then.finalMetadata (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel.js:111:51)
  at <anonymous>
  at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```
These errors are unhandled because they are not generated by my code and actually occur during server idle times.

After this error appears, **any and all** writes to Firestore result in:
```
DEADLINE_EXCEEDED: Deadline exceeded at callErrorFromStatus (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:30:26) 
at Http2CallStream.call.on (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call.js:79:34) 
at emitOne (events.js:121:20)
at Http2CallStream.emit (events.js:211:7) 
at process.nextTick (/app/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/call-stream.js:75:22) 
at _combinedTickCallback (internal/process/next_tick.js:132:7) 
at process._tickDomainCallback (internal/process/next_tick.js:219:9)
```

These problems (and similar) are described in various GitHub issues such as:
https://github.com/grpc/grpc-node/issues/734
https://github.com/googleapis/nodejs-firestore/issues/739

It seems a new `@grpc/grpc-js` version (0.6.13), new `google-gax` version and new `@google-cloud/firestore` (3.0.0) packages have been released (this is the dependency trail from `firebase-admin`) to address this issue but they cannot be used with firebase-admin that still requires `@google-cloud/firestore ^2.6.0` (= in practice 2.6.1).
Is there a plan to release an update to `firebase-admin` package to include these fixes?

**Comment by schmidt-sebastian** [comment]
Please install Firebase Admin from this branch for now:

```
 "dependencies": {
    "firebase-admin": "git+https://github.com/firebase/firebase-admin-node.git#firestore-30"
  }
```

This will include `@google-cloud/firestore` 3.0.

**Comment by shaibt** [comment]
Hey @schmidt-sebastian ,

Tried updating the firebase-admin dependency but after installing the branch you mentioned I got this error on firebase init and cannot load firebase at all now:
```
TypeError: instance.INTERNAL.registerComponent is not a function
    at registerDatabase (....../node_modules/@firebase/database/dist/index.node.cjs.js:15168:39)
    at Object.<anonymous> (....../node_modules/@firebase/database/dist/index.node.cjs.js:15200:5)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at DatabaseService.getDatabase (......./node_modules/firebase-admin/lib/database/database.js:64:24)
```
This is the only change I made ("8.8.0" -> "git+https://github.com/firebase/firebase-admin-node.git#firestore-30")
I've seen this error mentioned in a few issue threads ([714](https://github.com/firebase/firebase-admin-node/issues/714#issuecomment-562699156),[722](https://github.com/firebase/firebase-admin-node/issues/722)) but don't understand what the solution is here.

**Comment by shaibt** [comment]
@schmidt-sebastian I upgraded all production servers to the new official firebase-admin package ver 8.9.0 that includes firebase 3.0.0. Hope this is the last I see of these connectivity issues :-)
