### ISSUE TITLE
[Firestore] IN query not working. Invalid 'opStr'

### ISSUE THREAD

**Issue by hkchakladar** [firebase/firebase-admin-node#767]
### [READ] Step 1: Are you in the right place?
Yes

### [REQUIRED] Step 2: Describe your environment

  * Firebase SDK version: `firebase-admin": "^8.2.0"`
  * Firebase Product: Firestore

### [REQUIRED] Step 3: Describe the problem

As described in [this blog](https://firebase.googleblog.com/2019/11/cloud-firestore-now-supports-in-queries.html) and [firestore documentation](https://firebase.google.com/docs/firestore/query-data/queries#in_and_array-contains-any), `IN` query is now supported. But when I run this query,

```js
firestore.collection("transactions")
		.where("uid", "==", uid)
		.where("number", "==", number)
		.where("status", "in", ["pending", "success"])
		.where("type", "==", type)
		.orderBy(admin.firestore.FieldPath.documentId(), "desc").limit(1).get()
```
 I get the following error:
```js
Error: Value for argument "opStr" is invalid. Acceptable values are: <, <=, ==, >, >=, array-contains
    at Object.validateEnumValue (/srv/node_modules/@google-cloud/firestore/build/src/validate.js:291:15)
    at validateQueryOperator (/srv/node_modules/@google-cloud/firestore/build/src/reference.js:1797:16)
    at Query.where (/srv/node_modules/@google-cloud/firestore/build/src/reference.js:954:17)
    at exports.createoid_v2.functions.runWith.https.onCall (/srv/index.js:2367:4)
    at func (/srv/node_modules/firebase-functions/lib/providers/https.js:318:32)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
```

**Comment by hkchakladar** [comment]
Fixed by using :

`Firebase SDK version: firebase-admin": "^8.9.0"`

**Comment by schmidt-sebastian** [comment]
Thanks for letting us know that you managed to make this work!

**Comment by thifil** [comment]
Hi
I am receiving the same error 
`Error: Value for argument "opStr" is invalid. Acceptable values are: <, <=, ==, >, >=, array-contains`
when using the `in` operator in google cloud functions. I've installed the latest firebase sdk using 
`npm install firebase-functions@latest firebase-admin@latest --save` and also updated the firebase tools using `npm i -g firebase-tools`

I am importing: 
`import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';`

and that's my query:
let size = 10;
        let items = afterData.requested.slice(i,size);
        i = i + size;
        console.log(items)
        await admin.firestore().collection("users")
        //@ts-ignore
        .where("phnr","in",items)
        .get()
        .then((querySnapshot: admin.firestore.QuerySnapshot) => {})

How can I make this work?

![grafik](https://user-images.githubusercontent.com/29702965/76622869-a9d06b00-6532-11ea-8b59-07179a96468b.png)

**Comment by hkchakladar** [comment]
@thifil update your `firebase-admin` version.

**Comment by jfalconmusik** [comment]
Updating my firebase-admin seems to have had no effect.

**Comment by ryan-saffer** [comment]
I am experiencing this issue too, and am using `firebase-admin: "^8.9.0"` in my `package.json`, and am running version `8.5.0` of the firebase CLI.

**Code**
```
 db.collection('bookings')
        .where('dateTime', '>', startDate)
        .where('dateTime', '<', endDate)
        .where('location', 'in', ['malvern', 'balwyn', 'mobile'])
        .get()
```
**Output**

```
Error: Value for argument "opStr" is invalid. Acceptable values are: <, <=, ==, >, >=, array-contains
    at Object.validateEnumValue (/workspace/node_modules/@google-cloud/firestore/build/src/validate.js:310:15)
    at validateQueryOperator (/workspace/node_modules/@google-cloud/firestore/build/src/reference.js:1813:16)
    at Query.where (/workspace/node_modules/@google-cloud/firestore/build/src/reference.js:955:17)
    at Promise (/workspace/lib/src/bookings/index.js:107:14)
    at new Promise (<anonymous>)
    at exports.sendOutForms.functions.pubsub.schedule.timeZone.onRun (/workspace/lib/src/bookings/index.js:92:12)
    at cloudFunction (/workspace/node_modules/firebase-functions/lib/cloud-functions.js:115:23)
    at Promise.resolve.then (/layers/google.nodejs.functions-framework/functions-framework/node_modules/@google-cloud/functions-framework/build/src/invoker.js:330:28)
    at process._tickCallback (internal/process/next_tick.js:68:7) 
```
Is anyone else experiencing this?

**Comment by schmidt-sebastian** [comment]
You are likely using an outdated version of Firestore. Please remove your package lock file and your `node_modules` folder and re-install.
