### ISSUE TITLE
TypeError: Cannot read property 'navigator' of undefined

### ISSUE THREAD

**Issue by moander** [firebase/firebase-admin-node#77]
I experience this error when running mocha with --use_strict argument

Version 4.2.1
node v6.11.2
mocha v3.5.0

```
TypeError: Cannot read property 'navigator' of undefined
    at node_modules\firebase-admin\lib\database\database.js:39:492
    at Object.<anonymous> (node_modules\firebase-admin\lib\database\database.js:254:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules\firebase-admin\lib\index.js:11:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules\firebase-functions\lib\apps.js:25:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules\firebase-functions\lib\providers\database.js:25:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules\firebase-functions\lib\index.js:32:16)
```

**Comment by hiranya911** [comment]
What exactly are you trying to achieve? If you want to run Admin SDK test suites just follow the instructions at https://github.com/firebase/firebase-admin-node/blob/master/CONTRIBUTING.md#running-tests

**Comment by moander** [comment]
It's my own test cases that fails to run.

All tests referencing firebase-admin fails with this error.

**Comment by damianobarbati** [comment]
+1 for this bug when running with `--use_strict`

```
0|adminify | TypeError: Cannot read property 'navigator' of undefined
0|adminify |     at /Users/damz/Desktop/adminify/node_modules/firebase-admin/lib/database/database.js:53:492
```

**Comment by hiranya911** [comment]
We simply reuse the database code provided in https://github.com/firebase/firebase-js-sdk

However, we depend on a fairly old version of it. I'm hoping upgrading to the latest version of database code might help alleviate some of these issues (database code underwent some major improvements recently, including TypeScript integration). Will keep this thread posted.

**Comment by thiemnd** [comment]
error same with me
TypeError: Cannot read property 'navigator' of undefined

**Comment by mesqueeb** [comment]
I got the same error, however, I don't even use strict.

I just did all these steps:

1. `git clone https://github.com/firebase/firebaseui-web.git`
2. `cd firebaseui-web`
3. `npm install`
4. `npm run build`

And then I get this bug.
However, when installing from NPM directly and `require()` from the node_modules it works fine.

**Comment by hiranya911** [comment]
Can somebody try this with a recent Admin SDK release (5.5.0 or higher)? We now use the latest database code from the JS SDK.

**Comment by mesqueeb** [comment]
I solved it by adding the built `firebaseui.js` file to the ignore list of `.babelrc`

**Comment by hiranya911** [comment]
I'm going to close this since there hasn't been any updates from the reporter in a while. I also believe this may have been fixed by our recent upgrade of the RTDB client code. Feel free to comment/reopen if the problen reappears.

**Comment by TimmDay** [comment]
I'm getting a similar error... I'm building a react project, and used yarn as a package manager. It looks like everything is where it should be in the node-modules folder.

when using `import * as firebase from 'firebase';` in a js file I get:
```
    auth.esm.js:10 Uncaught TypeError: Cannot read property 'navigator' of undefined
    at auth.esm.js:10
    at Object.<anonymous> (auth.esm.js:314)
    at Object../node_modules/@firebase/auth/dist/auth.esm.js (bundle.js:809)
    at __webpack_require__ (bootstrap:19)
    at Object../node_modules/firebase/dist/index.cjs.js (index.cjs.js:7)
    at __webpack_require__ (bootstrap:19)
    at Object../src/firebase/firebase.js (firebase.js:8)
    at __webpack_require__ (bootstrap:19)
    at Object../src/actions/auth.js (auth.js:1)
    at __webpack_require__ (bootstrap:19)
```
If I replace:
`import * as firebase from 'firebase';`
with
`const firebase = require("firebase/app");`
`require("firebase/database");`
Then everything works, but as soon as I include:
`require("firebase/auth");`
then I again get a "Cannot read property 'navigator' of undefined"

How can we make sure that this navigator thing is defined?
Sorry if this is a dumb question, but I am quite stumped.

**Comment by hiranya911** [comment]
@TimmDay please move your question to [JS SDK](https://github.com/firebase/firebase-js-sdk). It doesn't look like your issue has anything to do with the Admin SDK.

**Comment by sturmenta** [comment]
What I did was:

- Do not use the latest version of firebase, but the [version that indicate that you use](https://firebase.google.com/docs/firestore/quickstart?hl=es-419)
`npm install firebase@4.12.1 --save`

- Replace

```javascript
import * firebase from 'firebase';
import '@ firebase/firestore';
import '@ firebase/messaging';
```

by

```javascript
import * firebase from 'firebase';
import 'firebase/firestore';
import 'firebase/messaging';
```

- `npm i -S @firebase/firestore` `npm i -S @firebase/messaging`

And everything worked correctly!

**Comment by daniele-pecora** [comment]
For me it helper to **update** the **webpack** the **latest version** *4.17.1*.

This error arose when I tried to run 
- *angular 6*
- *angularfire2@5.0.0-rc.12-next* 
- *firebase@5.4.2*
- _*webpack@4.4.1*_ 

After updating **webpack** to the latest version the error vanished.
