### ISSUE TITLE
Firebase realtime database transaction maxretry error with a particular decimal number 63.99999999999999

### ISSUE THREAD

**Issue by hkchakladar** [firebase/firebase-admin-node#779]
I'm using Firebase Realtime Database transaction to update a node.

See the following code:

```js
const addVal = 3.74;
return admin.database().ref(`admin/test/node`).transaction((current_value) => {
    return (current_value || 0) + addVal;
});
```

It works fine generally. But this gives maxrety 1-2 error randomly in a week (Not sure about the reason, may be due to high contention?).

But this time there is a particular problem when the node value is particular decimal values, it starts giving maxrety errors everytime.

In the above case, when `current_value = 63.99999999999999` existing in the node, the transactions never succeed. It throws the following error everytime:

`current_value = 62.99999999999999` or `64.99999999999999` or `64` works fine.

```js
Error: maxretry
    at Repo.rerunTransactionQueue_ (/srv/node_modules/@firebase/database/dist/index.node.cjs.js:14629:67)
    at Repo.rerunTransactions_ (/srv/node_modules/@firebase/database/dist/index.node.cjs.js:14534:10)
    at /srv/node_modules/@firebase/database/dist/index.node.cjs.js:14513:19
    at /srv/node_modules/@firebase/database/dist/index.node.cjs.js:11946:17
    at PersistentConnection.onDataMessage_ (/srv/node_modules/@firebase/database/dist/index.node.cjs.js:11976:17)
    at Connection.onDataMessage_ (/srv/node_modules/@firebase/database/dist/index.node.cjs.js:11290:14)
    at Connection.onPrimaryMessageReceived_ (/srv/node_modules/@firebase/database/dist/index.node.cjs.js:11284:18)
    at WebSocketConnection.onMessage (/srv/node_modules/@firebase/database/dist/index.node.cjs.js:11185:27)
    at WebSocketConnection.appendFrame_ (/srv/node_modules/@firebase/database/dist/index.node.cjs.js:10773:18)
    at WebSocketConnection.handleIncomingFrame (/srv/node_modules/@firebase/database/dist/index.node.cjs.js:10824:22)
```

Note: The node is not being written by other clients. This is for testing.

**Comment by schmidt-sebastian** [comment]
@hkchakladar Thanks for reporting. You are likely hitting an issue with rounding errors either in the Node client, in the JSON transmission or on the backend. Our transaction code is however quite gnarly, and attempts to fix these errors in the past have caused regressions. I will keep this issue in mind for when we do overhaul this part of the codebase, but I would suggest to find a workaround on your end in the interim.

**Comment by rhodgkins** [comment]
I had a similar issue with large numbers (https://github.com/firebase/firebase-js-sdk/issues/2304) but was told that much focus wasn't on the RTDB anymore :-/

We worked around a similar issue with rounding by converting the number back and forth from a string which worked but wasn't ideal!

**Comment by xesunny** [comment]
Having the same issue again and again.

**Comment by itsmeneartou** [comment]
Started facing this issue today.

**Comment by schmidt-sebastian** [comment]
Closing this due to inactivity. Please re-open if this is still an issue.
