### ISSUE TITLE
TypeError: instance.INTERNAL.registerComponent is not a function (v8.10)

### ISSUE THREAD

**Issue by jamescrowley** [firebase/firebase-admin-node#828]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Catalina
  * Firebase SDK version: 8.10
  * Firebase Product: database
  * Node.js version: 12.16.1
  * Yarn version: 1.22.4

### [REQUIRED] Step 3: Describe the problem

Fresh installing firebase-admin. A call to 'admin.database()' (where admin is the imported firebase SDK) results in

```
TypeError: instance.INTERNAL.registerComponent is not a function
    at registerDatabase (/XXX/test/node_modules/@firebase/database/dist/index.node.cjs.js:15320:39)
    at Object.<anonymous> (/XXX/test/node_modules/@firebase/database/dist/index.node.cjs.js:15353:5)
```

I have reviewed the previous issues in the repo (https://github.com/firebase/firebase-admin-node/issues/717, https://github.com/firebase/firebase-admin-node/issues/722 etc), but the @firebase/app isn't referenced directly, nor does it appear at the top of the node_modules folder structure, in this project or in any parent folders.

#### Steps to reproduce:

1. `yarn init`
2. `yarn add firebase-admin`
3. Add code below
4. `node pushToFirebase.js`

#### Relevant Code:

```
'use strict';
const firebase = require("firebase-admin");

const serviceAccount = require('./serviceAccountKey.json')
firebase.initializeApp({
  credential: firebase.credential.cert(serviceAccount),
  databaseURL: process.env.FIREBASE_ENDPOINT
});
var ref = firebase
  .database()
  .ref(`/devices/${payload.device_id}/latestData`)
```

The yarn.lock can be viewed here: https://gist.github.com/jamescrowley/8274fac3230ea7be13506cdd44c64d51

*update* I tried with NPM too and hit the same issue. I must be missing something obvious here?! package-lock.json is here: https://gist.github.com/jamescrowley/9eae9e369ff2f8c85c0a8143f472b2f5

**Comment by jamescrowley** [comment]
This issue was resolved - there was indeed a stray node_modules further up in the file system, with an old version of the library.
