### ISSUE TITLE
firebase admin: FirebaseAppError: Service account object must contain a string "project_id" property.

### ISSUE THREAD

**Issue by zubeirtech** [firebase/firebase-admin-node#855]
environment

  * Operating System version: Windows 10
  * Firebase SDK version: 8.10.0
  * Firebase Product: auth
  * Node.js version: v12.16.1
  * NPM version: 6.13.4

**ServiceAccount Interface Conflict**

In order to initializeApp the sdk this is a step to add the credential property:
```javascript
admin.initializeApp({
    credential: admin.credential.cert({
        projectId: process.env.FIREBASE_PROJECT_ID,
        clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
        privateKey: process.env.FIREBASE_PK,
    }),
});
```
But my typescript compiler is giving me this error: 

```
FirebaseAppError: Service account object must contain a string "project_id" property.
    at FirebaseAppError.FirebaseError [as constructor] (C:\GIT\apps\letterman\letterman\node_modules\firebase-admin\lib\utils\error.js:42:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (C:\GIT\apps\letterman\letterman\node_modules\firebase-admin\lib\utils\error.js:88:28)
    at new FirebaseAppError (C:\GIT\apps\letterman\letterman\node_modules\firebase-admin\lib\utils\error.js:123:28)
    at new ServiceAccount (C:\GIT\apps\letterman\letterman\node_modules\firebase-admin\lib\auth\credential.js:134:19)
    at new ServiceAccountCredential (C:\GIT\apps\letterman\letterman\node_modules\firebase-admin\lib\auth\credential.js:68:15)
    at Object.cert (C:\GIT\apps\letterman\letterman\node_modules\firebase-admin\lib\firebase-namespace.js:219:58) ...... {
  errorInfo: {
    code: 'app/invalid-credential',
    message: 'Service account object must contain a string "project_id" property.'
  },
  codePrefix: 'app'
}
```

This is the interface of the Service Account:

```typescript
interface ServiceAccount {
    projectId?: string;
    clientEmail?: string;
    privateKey?: string;
  }
```

**Comment by hiranya911** [comment]
Following works fine for me:

```
const admin = require('firebase-admin');

admin.initializeApp({
  credential: admin.credential.cert({
      projectId: 'test-project',
      clientEmail: 'REDACTED',
      privateKey: 'REDACTED',
  }),
});
```

Make sure your `FIREBASE_PROJECT_ID` variable actually contains a non-empty value.

**Comment by zubeirtech** [comment]
Thank you @hiranya911 
my build was not updated, after updating it worked
