### ISSUE TITLE
Jests tests cannot run when firebase-admin is used.

### ISSUE THREAD

**Issue by lucbas** [firebase/firebase-admin-node#933]
* Operating System version: macOS 10.15.5
  * Firebase SDK version: "firebase-admin": "^8.9.2",
  * Firebase Product: auth, (messaging)
  * Node.js version: v12.18.2
  * NPM version: 6.14.5

#### Steps to reproduce:

I'm using firebase-admin in a node app to send messages.
In a file where I store re-usable functions, I have a firebase method that sends push notifications.

Unrelated to the firebase code, I want to test some functions in said, but Jest always fails with a firebase error.
I assume firebase is initialized because it is in the same file.

Command: `jest`

Result:

```shell

  ● Test suite failed to run

    Service account must be an object.

       5 | 
       6 | admin.initializeApp({
    >  7 |   credential: admin.credential.cert(APP.FIREBASE_ADMIN_KEY),
         |                                ^
       9 | });
      10 | 

      at FirebaseAppError.FirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:42:28)
      at FirebaseAppError.PrefixedFirebaseError [as constructor] (node_modules/firebase-admin/lib/utils/error.js:88:28)
      at new FirebaseAppError (node_modules/firebase-admin/lib/utils/error.js:123:28)
      at new ServiceAccount (node_modules/firebase-admin/lib/auth/credential.js:118:19)
      at new ServiceAccountCredential (node_modules/firebase-admin/lib/auth/credential.js:68:15)
      at Object.cert (node_modules/firebase-admin/lib/firebase-namespace.js:219:58)
      at Object.<anonymous> (src/libs/firebaseAdmin.ts:7:32)
```

`APP.FIREBASE_ADMIN_KEY` gets the firebase key over the `process.env.FIREBASE_ADMIN` environment variable, which in turn has the path to the admin key defined.

#### Relevant Code:

```typescript
import * as admin from 'firebase-admin';

admin.initializeApp({
  credential: admin.credential.cert(APP.FIREBASE_ADMIN_KEY),
});
```
 
When I start the application, there is no error with firebase and it works fine.

**Comment by lucbas** [comment]
I got it working with the following code inside the test:

```typescript
import * as admin from 'firebase-admin';

jest.mock('firebase-admin');
```
